### ISSUE TITLE
CUDA 9.0 support

### ISSUE THREAD

**Issue by AShedko** [JuliaGPU/CUDAnative.jl#102]
It would be nice to have support for the latest release, and to be able to build the whole CUDA setup for julia in a less hotchpotch fashion.
The release candidate is here:
https://developer.nvidia.com/cuda-release-candidate-download
The corresponding CUDNN release is here (albeit behind login):
https://developer.nvidia.com/cudnn

Currently none of the major framefork support this, so if Julia were to be first, we could get great people onboard.
I`m making this Issue because I am desperately failing to build the GPUArrays package.

**Comment by maleadt** [comment]
Basic support (ie. compatibility) is here already: #91

Please check if master suits your needs. I'll cherry-pick it onto stable then.

**Comment by AShedko** [comment]
Tests pass:
```
julia> Pkg.test("CUDAnative")
INFO: Testing CUDAnative
INFO: Testing using device GeForce GTX 1050 Ti
Documenter: setting up build directory.
Documenter: expanding markdown templates.
Documenter: building cross-references.
Documenter: running document checks.
 > checking for missing docstrings.
 > running doctests.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.

Test Summary: | Pass  Total
CUDAnative    |  124    124
INFO: CUDAnative tests passed
```
GPUArrays also works, except for CLFFT, but that may be my system`s problems.

**Comment by maleadt** [comment]
JuliaLang/METADATA.jl#10723
