### ISSUE TITLE
CUDA 9 ptxas doesn't support sm_20

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAnative.jl#103]
This shows as follows:

```
ptxas fatal   : Value 'sm_20' is not defined for option 'gpu-name'
```

I don't want to duplicate the compatibility database which now lives in CUDArt though...

**Comment by maleadt** [comment]
Worse, the CUDA version as detected in CUDAnative's `build.jl` comes from the driver, and thus might disagree with the toolkit version of binaries like `ptxas`. What a mess.

**Comment by maleadt** [comment]
```
for i in /home/tbesard/Work/CUDA/toolkit/*/bin/nvcc                                                                                                                            *[tb/bar_warp] 
do
$i --version | grep "Cuda compilation tools"
done
Cuda compilation tools, release 5.5, V5.5.0
Cuda compilation tools, release 6.0, V6.0.1
Cuda compilation tools, release 6.5, V6.5.12
Cuda compilation tools, release 7.0, V7.0.27
Cuda compilation tools, release 7.5, V7.5.17
Cuda compilation tools, release 8.0, V8.0.61
Cuda compilation tools, release 9.0, V9.0.102
Cuda compilation tools, release 7.5, V7.5.17
```

Looks pretty regular though, so CUDAapi should probably parse this.

**Comment by maleadt** [comment]
Maybe just warn if the detected toolkit version doesn't match the driver version.

**Comment by colbec** [comment]
I'm getting similar on openSUSE Leap 42.3 with CUDA 9. Build seems ok  but `Pkg.test("CUDAnative") ` fails with much output:
```
INFO: Testing using device GeForce GT 610
ptxas fatal   : Value 'sm_21' is not defined for option 'gpu-name'
...
```

in build a warning that I have multiple toolchains installed
```
INFO: Building CUDAnative
WARNING: Found multiple CUDA toolkit installations: /usr/local/cuda and /usr/local/cuda-9.0/targets/x86_64-linux
```
but in fact `/usr/local/cuda` is a symlink to `/usr/local/cuda-9.0/targets/x86_64-linux` but the build does not realize that.

**Comment by maleadt** [comment]
This issue shouldn't trigger, because the chosen compute model doesn't default to `sm_20` anymore but picks the most recent one compatible with your device. So that's a problem, in your case: GeForce GT 610 only supports up to `sm_21`, which isn't supported by CUDA 9's `ptxas` anymore. I assume you are using a CUDA driver with an older CUDA compatibility level (ie. `julia -e 'using CUDAdrv; @assert CUDAdrv.version() < v"9.0"'`), but installed a CUDA 9 toolkit on top of that?

**Comment by colbec** [comment]
My CUDA version reports as v"9.0.0" so the assert fails, but only because v"9.0.0" < v"9.0" fails.

I certainly upgraded my CUDA recently. I was using an old repo for openSUSE based on version 13.2 which provided CUDA 6,7, or 8, and managing these was a big problem from my Leap 42.3. Then I found a newer repo for Leap 42.2 which provides only CUDA 9. This installed without a problem. It does mean that a large proportion of my CUDA tests fail because the device does not support a lot of the newer functionality, however the test routine does complete and provides a report of what fails.

**Comment by maleadt** [comment]
Oh right, I assumed only the `code_sass` tests failed with the `ptxas` error you mentioned. But since you're actually using CUDA 9.0, which your device isn't compatible with, I would assume all codegen tests fail?

**Comment by colbec** [comment]
All tests pass for CUDAdrv.
FYI I have created a gist at https://gist.github.com/colbec/d32af4343680ac4616e9c096fdade031 which shows what fails using CUDA 9 on my GT 610.
If you think I am muddying the water here by using CUDA 9 I will endeavour to go back to CUDA 6 or something more appropriate.

**Comment by maleadt** [comment]
> All tests pass for CUDAdrv.

Yes, because that merely tests API interactions. All code generation functionality (ie. which relies on the CUDA API being able to compile PTX code for `sm_21`, in your case) fails, rendering CUDAnative essentially useless for you.

So yeah, don't use CUDA 9 with your GPU. It's not a CUDAnative limitation, you won't be able to compile code using `nvcc` (for your GPU) either.
