### ISSUE TITLE
Kernel objects

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAnative.jl#120]
For generic code, we need to be able to query certain properties about the compiled kernel (shared memory usage, register pressure, etc) in order to determine optimal launch configuration (e.g. using the [occupancy API](https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-occupancy-api-simplifies-launch-configuration/)). Making kernels into objects with metadata and methods would be a good/required first step to create an interface for this.

**Comment by MikeInnes** [comment]
I think you removed the explicit `@kernel function vadd(...)` annotations, but we might ultimately need them. I think there are a few good reasons to have them:

* It's explicit that the function is (only) intended to run on the device, and can throw better errors if it's called normally
* It's easy for the macro to add necessary metadata as above (either `vadd` is a struct, or we define `metadata(::typeof(vadd)) = ...`)
* With good launch config heuristics in place, calling `vadd(...)` could transparently launch a kernel without the `@cuda` macro.

**Comment by maleadt** [comment]
I've been wary of explicit `@kernel`/`@target ptx` annotations, as they discourage writing generic code. We'll need something like it though to mark GPU-specific methods when switching to Cassette for dispatch overloading.

That said, in this case I was rather thinking of making the internal compiler machinery instantiate a callable `KernelObject` for introspection purposes, and not really changing the external interface (yet).
For example:

```julia
@cuda (dims...,) foobar(foo, bar)
# expands to
kernel = CUDAnative.compile(foobar, Tuple{typeof(foo), typeof(bar)})
launch(kernel, (dims...,), foo, bar)
```

making it possible for library functions to not use the `@cuda` shorthand, but use `compile` and `launch` manually such that the library can inspect the properties of the kernel object (register usage, shared memory usage) and figure out a good launch configuration.

**Comment by vchuravy** [comment]
Yeah that would seem like the right abstraction. 

@denizyuret has asked me for something similar, specifically the ability to export a kernel to a NVTPX IR file.
