### ISSUE TITLE
Package build does not find libdevice

### ISSUE THREAD

**Issue by luis-sarro** [JuliaGPU/CUDAnative.jl#130]
Hi,

I am trying to build CUDAnative in a centos system but the build fails with the following error message:

```
INFO: Building CUDAnative
WARNING: CUDA 9.0 is only supported on Julia 0.7, intra-thread intrinsics (shuffle, vote, ...) might yield wrong results (see #107)
WARNING: Found multiple CUDA toolkit installations: / and /usr
=============================[ ERROR: CUDAnative ]==============================

LoadError: Could not find libdevice
while loading /home/lsb/.julia/v0.6/CUDAnative/deps/build.jl, in expression starting on line 175_
````

The details are the following: 

```
LSB Version: core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.3.1611 (Core)
Release: 7.3.1611
Codename: Core

NVIDIA driver version: 2:384.90
CUDA libraries: 1:8.0 except CUDANN (1:7.0)

Titan-X card.

julia v0.6 Version 0.6.0 (2017-06-19 13:05 UTC) 
```

I have found what I think are the libdevice libraries in /usr/share/cuda:

```
ls /usr/share/cuda
cudnn_samples_v7            libdevice.compute_30.10.bc  samples
demo_suite                  libdevice.compute_35.10.bc
libdevice.compute_20.10.bc  libdevice.compute_50.10.bc
```

I included this directory in my env. variables 
```
export LD_LIBRARY_PATH=/usr/local/lib:/usr/share/cuda:${LD_LIBRARY_PATH}
export DL_LOAD_PATH=/usr/share/cuda:${DL_LOAD_PATH}
```

with no success so far.

I would be extremely grateful if you could point me to what I am doing wrong. Thank you very much in advance.

Luis

**Comment by maleadt** [comment]
(took the liberty of formatting your post a little)

Could you run the following: `TRACE=1 julia --compilecache=no -e 'Pkg.build("CUDAnative")'`, as per the [troubleshooting section](https://juliagpu.github.io/CUDAnative.jl/stable/man/troubleshooting.html) of the manual? That should, among other things, list the directories `libdevice` is being looked for. Although I must already say that a detection of CUDA at `/` seems pretty weird already.

**Comment by luis-sarro** [comment]
Thank you very much for your rapid response. Here is the last block of the output:

```
DEBUG: CUDA toolkit at / identified as 8.0.61
DEBUG: Looking for libdevice in /
TRACE: Finding libdevice in String["//libdevice", "//nvvm/libdevice"]
=============================[ ERROR: CUDAnative ]==============================

LoadError: Could not find libdevice
while loading /home/lsb/.julia/v0.6/CUDAnative/deps/build.jl, in expression starting on line 175
```

Luis

**Comment by maleadt** [comment]
CUDAapi apparently thinks `/` is your CUDA toolkit prefix, based on either a faulty environment variable (CUDA_PATH, CUDA_HOME or CUDA_ROOT), the location of libcudart, or the location of nvcc. Next, libdevice should reside in the libdevice subdir of the CUDA toolkit prefix, in your case `/libdevice`, which is wrong. This should be enough information to debug the issue? Please keep us informed!

If you don't discover the issue, I can add some extra logging to CUDAnative/CUDAapi to print even more about its reasoning. But do post the _full_ log next time.

**Comment by luis-sarro** [comment]
Hi.

For the record:

we solved the problem by creating the links as 
```
mkdir /usr/local/cuda ; mkdir /usr/local/cuda/nvvm/ ; ln -s /usr/share/cuda /usr/local/cuda/nvvm/libdevice
The problem is due to the negativo installation tree,

```
If anyone that visits this issue tries the solution above, remove the --compilecache=no flag in the debug command suggested by Tim.

Luis

**Comment by maleadt** [comment]
Good to hear you solved the problem!

The `compilecache` option is required, or the debugging functionality of CUDAapi wouldn't kick in. But as you've probably discovered, there's a bug with that option, but I'm in the process of fixing these issues.

Why exactly was `/` detected as CUDA root? Which files resided in your filesystem root?
