### ISSUE TITLE
Are arbitrary isbits immutables handled yet?

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGPU/CUDAnative.jl#15]
```Julia
using CUDAnative, CUDAdrv
const cu = CUDAnative
dev = CuDevice(0)
ctx = CuContext(dev)
@target ptx function kernel(A, b)
    @inbounds A[1] = imag(b)
    nothing
end
A = CuArray(zeros(Float32, (1,)));
x = Complex64(2,2)
@cuda (1, 1) kernel(A, x)

Array(A)
--> ERROR: Illegal memory access (CUDA error #700, ERROR_ILLEGAL_ADDRESS)
```
Replacing x with an CuArray of length one works!

**Comment by maleadt** [comment]
Confirmed. Yet another ABI mismatch. We're effectively re-implementing the x86 ABI in CUDAnative here, which is obviously nonsense but also quite hard to get right. Will be solved properly when we have hooks into the compiler, managing our own calling conventions. In the meantime, I'll look if I can hack around it.

**Comment by SimonDanisch** [comment]
Oh my ;) Thank you, this fixes it!
