### ISSUE TITLE
Support for Dynamic Parallelism

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/CUDAnative.jl#17]
Dynamic parallelism support might be necessary to integrate `cuBLAS` on the device side.

Resources:
- http://users.ece.gatech.edu/~sudha/academic/class/ece8823/Lectures/Module-6-Microarchitecture/cuda-dyn-par.pdf

**Comment by maleadt** [comment]
Recursive functions are already supported on somewhat recent GPUs. Dynamic parallelism is mainly interesting to be able to saturate additional cores and drive compute.

Clang [doesn't support it I think](https://github.com/llvm-mirror/clang/blob/8a8f86873029d28fd7ab8c1edecbc93da6a638a1/lib/Sema/SemaCUDA.cpp#L124-L128), so I'm not sure whether LLVM does.

**Comment by vchuravy** [comment]
There is some documentation on page 166 of http://docs.nvidia.com/cuda/pdf/CUDA_Dynamic_Parallelism_Programming_Guide.pdf for using dynamic parallelism from NVPTX.

> C.3.2.1.1. cudaLaunchDevice
> At the PTX level, `cudaLaunchDevice()` needs to be declared in one of the two forms
> shown below before it is used.

```
// PTX-level Declaration of cudaLaunchDevice() when .address_size is 64
.extern .func(.param .b32 func_retval0) cudaLaunchDevice
(
 .param .b64 func,
 .param .b64 parameterBuffer,
 .param .align 4 .b8 gridDimension[12],
 .param .align 4 .b8 blockDimension[12],
 .param .b32 sharedMemSize,
 .param .b64 stream
)
;
// PTX-level Declaration of cudaLaunchDevice() when .address_size is 32
.extern .func(.param .b32 func_retval0) cudaLaunchDevice
(
 .param .b32 func,
 .param .b32 parameterBuffer,
 .param .align 4 .b8 gridDimension[12],
 .param .align 4 .b8 blockDimension[12],
 .param .b32 sharedMemSize,
 .param .b32 stream
)
;
```

> The CUDA-level declaration below is mapped to one of the aforementioned PTX-level
> declarations and is found in the system header file cuda_device_runtime_api.h.
> The function is defined in the cudadevrt system library, which must be linked with a
> program in order to use device-side kernel launch functionality.

**Comment by maleadt** [comment]
Oh that's just a global extern function, should be easy.

**Comment by vchuravy** [comment]
There is also `cudaGetParameterBuffer` that needs to be defined similarly. 
Some more information is available at https://github.com/nvidia-compiler-sdk/nvvmir-samples/blob/master/device-side-launch/Device-Side-Launch.txt

I don't quite now whether we need to support the `v2` versions of those two functions or the original versions, see https://github.com/nvidia-compiler-sdk/nvvmir-samples/blob/master/device-side-launch/gpu64.ll

We might be able to use the parameter buffer to pass immutable between functions.

**Comment by maleadt** [comment]
`v2` functions or not depend on the driver version. In the case of CUDA compilation the correct function is selected by means of conditional definitions in headers. We also need to do this [for CUDAdrv](https://github.com/JuliaGPU/CUDAdrv.jl/blob/0bd677a3f147823144acc3aab3f3c365b77f573c/src/version.jl#L17-L125).

**Comment by oschulz** [comment]
Just curious, is this still on the table? May be a nice feature to have in the long run.

**Comment by maleadt** [comment]
It's not "off the table", but I haven't spent any time on it either. Launch times have decreased significantly (with recent CUDA releases), and I haven't encountered many use cases for the feature, so I'm not planning on working on this any time soon.

**Comment by oschulz** [comment]
Thanks for the info, @maleadt! I was just curious about the long term plans (I have no immediate/specific application in mind here).

**Comment by vchuravy** [comment]
I played around with this for a bit and the NVVM example is a red-herring since the most likely handle it in the NVVM compiler and not part of libdevice. That means we probably have to write the assembly declaration.

```
julia> function getParameterBuffer(func, gridDim, blockDim, shmemSize)
         Base.llvmcall(("""
         declare i8* @cudaGetParameterBufferV2(i8*, {i32, i32, i32}, {i32, i32, i32}, i32)
         """, """
           %ptr = call i8* @cudaGetParameterBufferV2(i8* null, {i32, i32, i32} {i32 1, i32 1, i32 1}, {i32, i32, i32} { i32 1, i32 1, i32 1 }, i32 0)
           %ptr.i = ptrtoint i8* %ptr to i64
           ret i64 %ptr.i
         """), Ptr{UInt8}, Tuple{})
       end
getParameterBuffer (generic function with 1 method)

julia> function f() 
         getParameterBuffer(0,0,0,0)
         return nothing
       end
f (generic function with 1 method)

julia> @cuda f()
┌ Warning: The two argument form of `func_for_method_checked` is deprecated. Pass sparams in addition.
│   caller = irgen(::CUDAnative.CompilerContext) at irgen.jl:111
└ @ CUDAnative ~/.julia/packages/CUDAnative/QvP9a/src/compiler/irgen.jl:111
[ Info: Building the CUDAnative run-time library for your sm_70 device, this might take a while...
ERROR: InvalidIRError: compiling f() resulted in invalid LLVM IR
Reason: unsupported call to an unknown function (call to cudaGetParameterBufferV2)
Stacktrace:
 [1] getParameterBuffer at REPL[2]:2
 [2] f at REPL[3]:2
Stacktrace:
 [1] check_ir at /ccs/home/vchuravy/.julia/packages/CUDAnative/QvP9a/src/compiler/validation.jl:77 [inlined]
 [2] compile(::CUDAnative.CompilerContext) at /ccs/home/vchuravy/.julia/packages/CUDAnative/QvP9a/src/compiler/driver.jl:90
 [3] #cufunction#110(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(cufunction), ::typeof(f), ::Type{Tuple{}}) at /ccs/home/vchuravy/.julia/packages/CUDAnative/QvP9a/src/compiler/driver.jl:38
 [4] cufunction(::typeof(f), ::Type) at /ccs/home/vchuravy/.julia/packages/CUDAnative/QvP9a/src/execution.jl:240
 [5] top-level scope at /ccs/home/vchuravy/.julia/packages/CUDAnative/QvP9a/src/execution.jl:208
 [6] top-level scope at gcutils.jl:87
 [7] top-level scope at /ccs/home/vchuravy/.julia/packages/CUDAnative/QvP9a/src/execution.jl:205
```

**Comment by maleadt** [comment]
> ERROR: InvalidIRError: compiling f() resulted in invalid LLVM IR
> Reason: unsupported call to an unknown function (call to cudaGetParameterBufferV2)

You can add exceptions to the validation mechanism here: https://github.com/JuliaGPU/CUDAnative.jl/blob/dc37a71024869034ecb58cfe65c0f9658ea60aa7/src/compiler/validation.jl#L101
