### ISSUE TITLE
make @cuda f(args...) work

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGPU/CUDAnative.jl#170]
Difficulty seems to be to get `GC.@preserve` working, since it seems to need the symbol of a variable. Would be no issue, if `GC.@preserve args::Tuple` would preserve all elements of the tuple.

**Comment by yuyichao** [comment]
It should

**Comment by SimonDanisch** [comment]
Great, so we just need to drop the `...` while preserving, and just add it back when splicing it into the cudaconvert tuple!
