### ISSUE TITLE
InferenceHooks, CodeGenHooks, etc?

### ISSUE THREAD

**Issue by habemus-papadum** [JuliaGPU/CUDAnative.jl#184]
Hi -- The "Effective Extensible Programming" paper mentions InferenceHooks, CodeGenHooks, etc.  They seem interesting and useful for some ideas I want to pursue.  Do these exist in the current julia and are they being used, or is CudaNative currently using some other solution?  If they don't exist, are there thoughts about providing these features at some point and a forum to discuss what they might look like?

thanks! nehal

**Comment by vchuravy** [comment]
Take a look at `irgen` in jit.jl to see how CUDAnative  interacts with base codegen. Especially here https://github.com/JuliaGPU/CUDAnative.jl/blob/6c1d8c9f38f2f1e21fe6930cbca6333ec3f947d7/src/jit.jl#L76

**Comment by habemus-papadum** [comment]
Thanks!  Looks like that is a good starting point. nehal

**Comment by maleadt** [comment]
`InferenceParams` are now regular `Params`: https://github.com/JuliaLang/julia/blob/master/base/compiler/params.jl
`InferenceHooks` have not been merged (old WIP at https://github.com/JuliaLang/julia/commit/02eebd316a4c44f035577ac4137bf3e96a24fbcc) and will probably be subsumed by a Cassette-based implementation

But yeah, the core `irgen` function is probably your best bet to implement a custom back-end with.

**Comment by habemus-papadum** [comment]
Thanks for pointing out `Params` and mentioning Cassette, which led me to Cassette.jl   I had come across the unmerged WIP for InferenceHooks which had led to my initial confusion, and questions about whether developing hooks into Julia's compilation process  had been abandoned or stalled, but it looks like it has some support and that more support is being investigated.   cheers, nehal
