### ISSUE TITLE
Launch out of resources error though no of threads are within limit.

### ISSUE THREAD

**Issue by americast** [JuliaGPU/CUDAnative.jl#188]
```julia
using CUDAnative, CUDAdrv

function matmul_kernel(A::AbstractArray{T}, out, Asize, ::Val{TS}, ::Val{TS²}) where {T, TS, TS²}
    row = threadIdx().x
    Asub = @cuStaticSharedMem(T, TS²)
    acc = T(0.0)
    for t in UInt32(1):UInt32(div(Asize[2], TS))
        # @cuprintf("Here: %d \n", t)
        for k in UInt32(1):UInt32(TS)
            @inbounds acc += Asub[(k - 1)+ (row - 1 ) + 1] * Asub[(row - 1) * TS + (k - 1) + 1]
        end
        sync_threads()
    end
    @inbounds out[row] = acc
    return
end

A = CuArray(rand(Float32, 32, 32))
out = similar(A)
@cuda ((1,1), (32, 32)) matmul_kernel(A, out, UInt32.(size(A)), Val{UInt32(32)}(), Val{UInt32(1024)}())
```

The code above gives an error `ERROR: LoadError: CUDA error: too many resources requested for launch (code #701, ERROR_LAUNCH_OUT_OF_RESOURCES)` on a GPU with a maximum capacity of 1024 threads. Interestingly, the error disappears if `@cuprintf` is executed (i.e. uncommented). Or, commenting out the line before `return` (the one that starts with `@inbounds`) also makes the error disappear (but naturally, serves no purpose). I was wondering what is going wrong here.

**Comment by SimonDanisch** [comment]
Btw, I can't reproduce this on julia 0.7! Not sure if Julia or CUDAnative master, or different gpu does the magic here ;)

**Comment by maleadt** [comment]
Can't reproduce either. @americast, could you try with your GPU on 0.7?

**Comment by americast** [comment]
@maleadt @SimonDanisch Me too! Working fine with 0.7. Here's the code I ran on 0.7:
```julia
using CUDAnative, CUDAdrv

function matmul_kernel(A::AbstractArray{T}, out, Asize, ::Val{TS}, ::Val{TS²}) where {T, TS, TS²}
    row = threadIdx().x
    Asub = @cuStaticSharedMem(T, TS²)
    acc = T(0.0)
    for t in UInt32(1):UInt32(div(Asize[2], TS))
        # @cuprintf("Here: %d \n", t)
        for k in UInt32(1):UInt32(TS)
            @inbounds acc += Asub[(k - 1)+ (row - 1 ) + 1] * Asub[(row - 1) * TS + (k - 1) + 1]
        end
        sync_threads()
    end
    @inbounds out[row] = acc
    return
end

A = CuArray(rand(Float32, 32, 32))
out = similar(A)
@cuda threads = (32, 32) matmul_kernel(A, out, UInt32.(size(A)), Val{UInt32(32)}(), Val{UInt32(1024)}())
```

Should this issue be closed?

**Comment by maleadt** [comment]
> Should this issue be closed?

I guess; just reopen if you encounter the issue again.
Now that we're working on the same branch again, it should be easier to fix incoming issues :slightly_smiling_face:
