### ISSUE TITLE
Int32(Float) constructor fails to compile

### ISSUE THREAD

**Issue by jmaebe** [JuliaGPU/CUDAnative.jl#21]
<pre><code>using CUDAdrv, CUDAnative

 function truncit(inval)
    aaa = Int32(inval)
    return nothing
 end

 dev = CuDevice(0)
 ctx = CuContext(dev)

 @cuda dev (1, 1) truncit(Float32(2.0))

 destroy(ctx)
</pre></code>

Julia output:
<pre>
ERROR: LoadError: LLVM error: Cannot select: t29: i64 = ExternalSymbol'truncf'
In function: julia_convert_62240
 in handle_error(::Cstring) at /home/nipennem/Documents/julia/julia-cuda/.julia/release/v0.6/LLVM/src/core/context.jl:96
 in LLVMTargetMachineEmitToMemoryBuffer(::Ptr{LLVM.API.LLVMOpaqueTargetMachine}, ::Ptr{LLVM.API.LLVMOpaqueModule}, ::UInt32, ::Base.RefValue{Cstring}, ::Base.RefValue{Ptr{LLVM.API.LLVMOpaqueMemoryBuffer}}) at /home/nipennem/Documents/julia/julia-cuda/.julia/release/v0.6/LLVM/deps/../lib/3.9/libLLVM_h.jl:301
 in emit(::LLVM.TargetMachine, ::LLVM.Module, ::UInt32) at /home/nipennem/Documents/julia/julia-cuda/.julia/release/v0.6/LLVM/src/targetmachine.jl:39
 in mcgen(::LLVM.Module, ::LLVM.Function, ::VersionNumber) at /home/nipennem/Documents/julia/julia-cuda/.julia/release/v0.6/CUDAnative/src/jit.jl:267
 in compile_function(::CUDAdrv.CuDevice, ::Any, ::Any) at /home/nipennem/Documents/julia/julia-cuda/.julia/release/v0.6/CUDAnative/src/jit.jl:338
 in cufunction(::CUDAdrv.CuDevice, ::Any, ::Any) at /home/nipennem/Documents/julia/julia-cuda/.julia/release/v0.6/CUDAnative/src/jit.jl:355
 in macro expansion at /home/nipennem/Documents/julia/julia-cuda/.julia/release/v0.6/CUDAnative/src/execution.jl:191 [inlined]
 in #generated_cuda#43(::Array{Any,1}, ::CUDAnative.#generated_cuda, ::CUDAdrv.CuDevice, ::Tuple{Int64,Int64}, ::#truncit, ::Float32) at /home/nipennem/Documents/julia/julia-cuda/.julia/release/v0.6/CUDAnative/src/execution.jl:177
 in generated_cuda(::CUDAdrv.CuDevice, ::Tuple{Int64,Int64}, ::#truncit, ::Float32, ::Vararg{Float32,N}) at /home/nipennem/Documents/julia/julia-cuda/.julia/release/v0.6/CUDAnative/src/execution.jl:177
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
 in process_options(::Base.JLOptions) at ./client.jl:271
 in _start() at ./client.jl:335
while loading /home/nipennem/Documents/julia/rodinia/julia_cuda/backprop/truncf.jl, in expression starting on line 11
</pre>
It's similar with a Float64, except that there the 'trunc' symbol is not found.

**Comment by maleadt** [comment]
Dup of #13. Use LLVM_VER=svn for `trunc` to work. Others might still be broken, not sure how to fix that yet (prevent emission through inference/codegen hooks, use compiler-rt in Julia to provide fallback implementations, ...).
