### ISSUE TITLE
@cuda hangs on 7.0-rc2 AArch64

### ISSUE THREAD

**Issue by mokus0** [JuliaGPU/CUDAnative.jl#224]
I have a freshly installed Julia 0.7.0-rc2 system (build from a clean clone of the tag on github) on a Jetson TX2, and am trying to get CUDAnative running.  The command `@cuda (()->@cuprintf("Testing...\n"))(); CUDAdrv.synchronize()` hangs without producing any output, error or otherwise.

Some info about the system:

```
mokus@feynman ~ $ uname -a
Linux feynman 4.4.38-tegra #1 SMP PREEMPT Thu Mar 1 20:49:20 PST 2018 aarch64 aarch64 aarch64 GNU/Linux
mokus@feynman ~ $ head -n1 /etc/nv_tegra_release 
# R28 (release), REVISION: 2.0, GCID: 10567845, BOARD: t186ref, EABI: aarch64, DATE: Fri Mar  2 04:57:01 UTC 2018
mokus@feynman ~ $ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-rc2.0 (2018-08-02 19:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  aarch64-linux-gnu

(v0.7) pkg> status
    Status `~/.julia/environments/v0.7/Project.toml`
  [c5f51814] CUDAdrv v0.8.4
  [be33ccc6] CUDAnative v0.8.5
  [3a865a2d] CuArrays v0.6.2
  [929cbde3] LLVM v0.9.12
  [ae9b84b9] Multirate v0.0.2+ #matrix-channelizer-experiment (https://github.com/mokus0/Multirate.jl)
  [bd07be1c] Winston v0.13.2

julia> using CUDAnative

julia> @cuda (()->@cuprintf("Testing...\n"))(); CUDAdrv.synchronize()

```

If anyone can suggest other places to look, I'm happy to collect data and attempt to fix the issue, but I'm fairly new to Julia and not really sure where to begin.

**Comment by mokus0** [comment]
Hmm, still not sure about the cause but a new build of the julia environment with USE_SYSTEM_LLVM=1 seems to have fixed it.

**Comment by maleadt** [comment]
Ah, `USE_SYSTEM_LLVM=1` _really_ isn't supported anymore, and this should work out of the box. I'll look into this some time soon.

**Comment by maleadt** [comment]
Can you replace with latest CUDAnative/CUDAdrv (from master) on 1.0?
If you kill the process, or attach a debugger to it, where does the backtrace point?

**Comment by mokus0** [comment]
Yes, I'll try that and get back to you.  I'm getting 1.0 set up currently.

**Comment by mokus0** [comment]
It appears the problem no longer occurs using julia's v1.0.0 tag.  I also realized that my previous build was not actually with system LLVM, but did switch to system libm, blas, lapack, gmp, and mpfr.  I can try it again with no system libraries if you'd like.

**Comment by mokus0** [comment]
ok, went ahead and set up to build without any of those system libs and tested again.  Seems to be working fine there now too.  Either it has been fixed or it was a weird fluke before.

**Comment by maleadt** [comment]
>  I can try it again with no system libraries if you'd like.

I'd generally recommend not using system libraries, especially with LLVM. But other than that, no need to spend time on this. I suspect this wasn't a hang in LLVM, but rather your GPU acting up. If it would happen again, try to interrupt and get hold of a backtrace. Feel free to reopen if it happens again!
