### ISSUE TITLE
Question:  Getting a "recursion not supported: error when compiling reduce.jl

### ISSUE THREAD

**Issue by MeBlueDolphin** [JuliaGPU/CUDAnative.jl#247]
Hi Tim,

  Firstly, many thanks for developing CUDAnative.jl.  I am trying to run your "reduce.jl" example with julia 0.7.0 on my PC laptop which has the 940MX card.  I am getting the following "recursion not supported error:"

```
julia> include("verify_reduce.jl")
ERROR: LoadError: GPU compilation failed, try inspecting generated code with any of the @device_code_... macros
CompilerError: could not compile reduce_grid(typeof(+), CuDeviceArray{Int32,1,CUDAnative.AS.Global}, CuDeviceArray{Int32,1,CUDAnative.AS.Global}, Int32); recursion is currently not supported
Stacktrace:
 [1] recurse_value_invocation at C:\Users\ismailb\.julia\packages\CUDAnative\FzmMm\src\cgutils.jl:233
 [2] shfl_down at C:\Users\ismailb\.julia\packages\CUDAnative\FzmMm\src\device\intrinsics\warp_shuffle.jl:70
 [3] split_value_invocation at C:\Users\ismailb\.julia\packages\CUDAnative\FzmMm\src\cgutils.jl:203
 [4] recurse_value_invocation at C:\Users\ismailb\.julia\packages\CUDAnative\FzmMm\src\cgutils.jl:233
 [5] reduce_block at C:\Users\ismailb\julia_code\reduce_cuda.jl:24
 [6] reduce_grid at C:\Users\ismailb\julia_code\reduce_cuda.jl:59 (repeats 2 times)
Stacktrace:
 [1] (::getfield(CUDAnative, Symbol("#hook_emit_function#55")){CUDAnative.CompilerContext,Array{Core.MethodInstance,1}})(::Core.MethodInstance, ::Core.CodeInfo, ::UInt64) at C:\Users\ismailb\.julia\packages\CUDAnative\FzmMm\src\compiler.jl:154
 [2] irgen(::CUDAnative.CompilerContext) at C:\Users\ismailb\.julia\packages\CUDAnative\FzmMm\src\compiler.jl:189
 [3] #compile_function#69(::Bool, ::Function, ::CUDAnative.CompilerContext) at .\logging.jl:308
 [4] compile_function at C:\Users\ismailb\.julia\packages\CUDAnative\FzmMm\src\compiler.jl:651 [inlined]
 [5] #cufunction#70(::Base.Iterators.Pairs{Symbol,typeof(reduce_grid),Tuple{Symbol},NamedTuple{(:inner_f,),Tuple{typeof(reduce_grid)}}}, ::Function, ::CuDevice, ::Any, ::Any) at C:\Users\ismailb\.julia\packages\CUDAnative\FzmMm\src\compiler.jl:714
 [6] (::getfield(CUDAnative, Symbol("#kw##cufunction")))(::NamedTuple{(:inner_f,),Tuple{typeof(reduce_grid)}}, ::typeof(cufunction), ::CuDevice, ::Function, ::Type) at .\none:0
 [7] _cuda(::CUDAnative.KernelWrapper{typeof(reduce_grid)}, ::typeof(reduce_grid), ::Tuple{}, ::NamedTuple{(:blocks, :threads),Tuple{Float64,Int64}}, ::typeof(+), ::CuDeviceArray{Int32,1,CUDAnative.AS.Global}, ::CuDeviceArray{Int32,1,CUDAnative.AS.Global}, ::Int32) at C:\Users\ismailb\.julia\packages\CUDAnative\FzmMm\src\execution.jl:219
 [8] macro expansion at .\gcutils.jl:87 [inlined]
 [9] gpu_reduce(::typeof(+), ::CuArray{Int32,1}, ::CuArray{Int32,1}) at C:\Users\ismailb\julia_code\reduce_cuda.jl:95
 [10] top-level scope at C:\Users\ismailb\julia_code\verify_reduce.jl:18
 [11] include at .\boot.jl:317 [inlined]
 [12] include_relative(::Module, ::String) at .\loading.jl:1038
 [13] include(::Module, ::String) at .\sysimg.jl:29
 [14] include(::String) at .\client.jl:398
 [15] top-level scope at none:0
in expression starting at C:\Users\ismailb\julia_code\verify_reduce.jl:15
```

What am I doing wrong?

Regards,
Ismail

**Comment by maleadt** [comment]
Please use triple ticks to delimit source code (@vchuravy has edited your post to include them).

There is no `verify_reduce.jl` file in CUDAnative.jl, and the reduce example works fine and is tested by CI. So please give some more details: _which_ reduce example are you running, and how? What version of CUDAnative?

**Comment by MeBlueDolphin** [comment]
Hi Tim,

   Thank you very much for your reply and my apology for double posting my question.  I am relatively new to Julia and did not see this thread until after I posted my question on your github repository. 

 I have the following versions installed on Julia 0.7.0:

    "CUDAnative" => v"0.8.9"
    "LLVM"       => v"0.9.14"
    "CUDAdrv"    => v"0.8.5"

  Please find below the two sample julia files. 

Best regards,
Ismail

`#verify_reduce.jl
using Test
include("reduce_cuda.jl")
#cuda_device = CuDevice(0)
ctx = CuCurrentContext()
dev = device(ctx)
if capability(dev) < v"3.0"
    warn("this example requires a newer GPU")
    exit(0)
end
len = 10^7
input = ones(Int32, len)
# CPU
cpu_val = reduce(+, input)
# CUDAnative
let
    gpu_input = CuArray(input)
    gpu_output = similar(gpu_input)
    gpu_reduce(+, gpu_input, gpu_output)
    gpu_val = Array(gpu_output)[1]
    @assert cpu_val == gpu_val
end`


`#reduce_cuda.jl
# Fast parallel reduction for Kepler hardware
# - uses shuffle and shared memory to reduce efficiently
# - support for large arrays
#
# Based on devblogs.nvidia.com/parallelforall/faster-parallel-reductions-kepler/
using CUDAdrv, CUDAnative
# Reduce a value across a warp

function reduce_warp(op::F, val::T) where {F<:Function, T}
    offset = CUDAnative.warpsize() / UInt32(2)
    # TODO: this can be unrolled if warpsize is known...
    while offset > 0
        val = op(val, shfl_down(val, offset))
        offset = offset / UInt32(2)
    end
    return val
end

# Reduce a value across a block, using shared memory for communication
function reduce_block(op::F, val::T) where {F<:Function,T}
    # shared mem for 32 partial `sums`
    shared = @cuStaticSharedMem(T, 32)
    # TODO: use fldmod1 (JuliaGPU/CUDAnative.jl#28)
    wid  = div(threadIdx().x-UInt32(1), CUDAnative.warpsize()) + UInt32(1)
    lane = rem(threadIdx().x-UInt32(1), CUDAnative.warpsize()) + UInt32(1)
    # each warp performs partial reduction
    val = reduce_warp(op, val)
    # write reduced value to shared memory
    if lane == 1
        @inbounds shared[wid] = val
    end
    # wait for all partial reductions
    sync_threads()
    # read from shared memory only if that warp existed
    @inbounds val = (threadIdx().x <= fld(blockDim().x, CUDAnative.warpsize())) ? shared[lane] : zero(T)
    # final reduce within first warp
    if wid == 1
        val = reduce_warp(op, val)
    end

# Reduce an array across a complete grid
function reduce_grid(op::F, input::CuDeviceArray{T,1}, 
                     output::CuDeviceArray{T,1}, len::Integer) where {F<:Function,T}
    # TODO: neutral element depends on the operator (see Base's 2 and 3 argument `reduce`)
    val = zero(T)
    # reduce multiple elements per thread (grid-stride loop)
    # TODO: step range (see JuliaGPU/CUDAnative.jl#12)
    i = (blockIdx().x-UInt32(1)) * blockDim().x + threadIdx().x
    step = blockDim().x * gridDim().x
    while i <= len
        @inbounds val = op(val, input[i])
        i += step
    end
    val = reduce_block(op, val)
    if threadIdx().x == UInt32(1)
        @inbounds output[blockIdx().x] = val
    end
    return
end

#Reduce a large array.
#Kepler-specific implementation, ie. you need sm_30 or higher to run this code.
function gpu_reduce(op::F, input::CuArray{T,1}, output::CuArray{T,1}) where {F<:Function,T}
    len = length(input)   
    # TODO: these values are hardware-dependent, with recent GPUs supporting more threads
    nthreads = 512
    nblocks = min((len + nthreads - 1) / nthreads, 1024)

    # the output array must have a size equal to or larger than the number of thread blocks
    # in the grid because each block writes to a unique location within the array.
    if length(output) < nblocks
        throw(ArgumentError("output array too small, should be at least $blocks elements"))
    end
    @cuda blocks=nblocks threads=nthreads reduce_grid(op, input, output, Int32(len))
    @cuda blocks=1 threads=1024 reduce_grid(op, output, output, Int32(blocks))

   return
end
`

**Comment by maleadt** [comment]
You have changed lots of things compared to the example that is part of CUDAnative.jl, so you shouldn't claim "the reduce.jl example does not run". Crucially, you changed `CUDAnative.warpsize() ÷ 2` to a regular division, resulting in a float, which `shfl_down` isn't applicable to. This inference failure leads to the `recurse_value_invocation` generator not exanding, confusingly triggering the recursion error.

**Comment by MeBlueDolphin** [comment]
Thank you Tim,

   That stems from my hitherto ignorance of the Julia language.  When I downloaded the raw version of your code, Julia complained when parsing the division character.  Please excuse my silly Julia language question, how do I write the division operator in Julia?

Greatly appreciated,
Ismail

**Comment by MeBlueDolphin** [comment]
Hi Tim,

   Please ignore my question, found the answer from JuliaDocs.

Greatly appreciated,
Ismail

**Comment by MeBlueDolphin** [comment]
Actually, my Julia installation is on Windows10.  I am using notepad as my editor.  In reduce_warp, when I input 

`offset= CUDAnative.warpsize() \div	2`

 I get the following error when Julia parses the unicode input above:

`julia> include("verify_reduce.jl")
ERROR: LoadError: LoadError: syntax: extra token "2" after end of expression
Stacktrace:
 [1] include at .\boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1038
 [3] include(::Module, ::String) at .\sysimg.jl:29
 [4] include(::String) at .\client.jl:398
 [5] top-level scope at none:0
 [6] include at .\boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1038
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] include(::String) at .\client.jl:398
 [10] top-level scope at none:0
in expression starting at C:\Users\ismailb\julia_code\reduce.jl:14
in expression starting at C:\Users\ismailb\julia_code\verify_reduce.jl:2`

  Is there a Window editor that supports Julia's unicode?

Thank you,
Ismail

**Comment by maleadt** [comment]
You're supposed to hit `tab` after enterin `\div2`, which of course only works in an editor that supports such a sequence. I'd recommend Juno, which is an Atom-based editor tailored to the Julia language.

> When I downloaded the raw version of your code, Julia complained when parsing the division character

How did you download the file then? I assume by copy/pasting from github into an editor? Because just downloading the files shouldn't have altered the contents, and they should have to parse just fine.
Instead of copy/pasting the contents, you could just download the CUDAnative repository as a zip. Or `dev` the entire thing using the package manager, but then you'd be using the master branch of CUDAnative which isn't guaranteed to be stable.

**Comment by MeBlueDolphin** [comment]
Thank you Tim,

    It works perfectly now.  I am curious about gpu_reduce's performance vs. (julia's cpu) reduce.  I ran "reduce.jl" with a vector of length **10e8** and got the following runtime results on my laptop:  

CPU:  i7-7820HQ@2.9GH, 4 cores, 26GB RAM,
GPU:  GeForce 940MX)

julia> include("verify_reduce.jl")
cpu
  0.033330 seconds (5 allocations: 176 bytes)
gpu
  0.143678 seconds (141.53 k allocations: 7.846 MiB)

  It is a bit puzzling why there is a slowdown with gpu_reduce.   Is this expected behavior given the vector length?

 I also, tried your v_add.jl example, the speedup there was a respectable 9x.   

Best regards.
Ismail

**Comment by maleadt** [comment]
These are examples, not indicative of realistic application loads. You need to profile properly if you want to know what's going on:

```
$ nvprof julia benchmark.jl
==17287== NVPROF is profiling process 17287, command: julia benchmark.jl
run(benchmark_cpu) = Trial(22.255 ms)
run(benchmark_gpu) = Trial(95.221 ms)
run(benchmark_cuda) = Trial(87.746 ms)
==17287== Profiling application: julia benchmark.jl
==17287== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   57.69%  4.29352s        50  85.870ms  84.451ms  93.437ms  [CUDA memcpy DtoH]
                   40.99%  3.05074s        50  61.015ms  60.113ms  67.182ms  [CUDA memcpy HtoD]
                    0.72%  53.608ms        56  957.28us  4.6720us  1.9200ms  sumReduce_grid(int*, int*, int)
                    0.61%  45.069ms        44  1.0243ms  5.8240us  2.1375ms  ptxcall_reduce_grid_2
```

ie. the actual kernel execution is 20x faster, only to be dwarfed by the memory transfer times.

But please don't keep on asking these support questions on the _issue_ tracker, that's what eg. Discourse or Slack is for.

**Comment by MeBlueDolphin** [comment]
Thank you Tim,

  And again my apology for the deluge of my out-of-context questions especially about the language itself, and greatly appreciate your taking the time to answer them.   Thank you for pointing out the profiling tools in Julia (am picking up speed on the language now).   Lastly, thank you for writing CUDAnative, I am finding it very helpful for quickly testing/prototyping CUDA implementations.

Much appreciated,
Ismail
