### ISSUE TITLE
Unhandled IR pattern in `throw` rewriting

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAnative.jl#258]
```
julia> broadcast!((x)->x[2], cu([1]), Ref((1,)))
┌ Warning: unreachable control flow with multiple predecessors
└ @ CUDAnative /home/tbesard/Julia/CUDAnative/src/compiler/irgen.jl:421
1-element CuArray{Float32,1}:
ERROR: a bounds_error exception occurred
 during kernel execution 1.0
```

**Comment by vchuravy** [comment]
Ok full module dump from #275 at https://gist.github.com/vchuravy/64c7f5372f23f5673a46ce0195c521ef#file-kernelf_3-opt-ll and https://gist.github.com/vchuravy/64c7f5372f23f5673a46ce0195c521ef#file-kernelf_3-unopt-ll (this is with #277 )

**Comment by maleadt** [comment]
Fixed https://github.com/JuliaGPU/CUDAnative.jl/pull/277
