### ISSUE TITLE
KernelError: kernel returns a value of type `Union{}`

### ISSUE THREAD

**Issue by artalvpes** [JuliaGPU/CUDAnative.jl#264]
When turning a vector addition example that was running correctly into a matrix multiplication (attached file), I've got the error below.

```
ERROR: LoadError: GPU compilation of kernel_madd(CuDeviceArray{Int64,1,CUDAnative.AS.Global}, CuDeviceArray{Int64,1,CUDAnative.AS.Global}, CuDeviceArray{Int64,1,CUDAnative.AS.Global}) failed
KernelError: kernel returns a value of type `Union{}`

Make sure your kernel function ends in `return`, `return nothing` or `nothing`.
If the returned value is of type `Union{}`, your Julia code probably throws an exception.
Inspect the code with `@device_code_warntype` for more details.
```

The return value is the same as the vector addition example. I have even reshaped the matrices as vectors before sending them to the GPU (to make the example more similar to the previous one) but it did not work.

[VertorAdd.jl.zip](https://github.com/JuliaGPU/CUDAnative.jl/files/2447267/VertorAdd.jl.zip)

**Comment by maleadt** [comment]
> The return value is the same as the vector addition example

That's impossible. A return value of type `Union{}` indicates an error is thrown. Did you inspect the kernel with `@device_code_warntype` like the error message says?

Also, please use triple quotes to delimit code output.

**Comment by artalvpes** [comment]
I'm sorry. I'm still a beginner in Julia. The output of the line
'''@device_code_warntype @cuda blocks=nbl threads=TperB kernel_madd(d_a,
d_b, d_c)''' is the following

'''WARNING: both CUDAnative and CUDAdrv export "warpsize"; uses of it in
module Main must be qualified
WARNING: both CUDAdrv and Base export "@elapsed"; uses of it in module Main
must be qualified
WARNING: both CUDAdrv and Base export "reset"; uses of it in module Main
must be qualified
Running in the Intel Core i7 CPU...
Running in GeForce GTX 850M GPU...
Body::Union{}
7 1 ─ %1  = Base.llvmcall::Core.IntrinsicFunction
             │╻╷╷╷╷ blockIdx
  │   %2  = (%1)(Ptr{Nothing} @0x0000000002719c08, UInt32,
Tuple{})::UInt32             ││┃│││  blockIdx_x
  │   %3  = (Core.zext_int)(Core.Int64, %2)::Int64
            │││╻     Type
  │   %4  = (Base.add_int)(%3, 1)::Int64
            │││╻     +
  │   %5  = Base.llvmcall::Core.IntrinsicFunction
             │││╻╷╷   _index
  │   %6  = (%5)(Ptr{Nothing} @0x00000000035515c8, UInt32,
Tuple{})::UInt32             ││││┃│    macro expansion
  │   %7  = (Core.zext_int)(Core.Int64, %6)::Int64
            ││││╻     toInt64
  │         (Base.add_int)(%7, 1)
             │││╻     +
  │   %9  = Base.llvmcall::Core.IntrinsicFunction
             │││╻╷╷   _index
  │   %10 = (%9)(Ptr{Nothing} @0x00000000020ae268, UInt32,
Tuple{})::UInt32             ││││┃│    macro expansion
  │   %11 = (Core.zext_int)(Core.Int64, %10)::Int64
             ││││╻     toInt64
  │         (Base.add_int)(%11, 1)
            │││╻     +
  │   %13 = (Base.sub_int)(%4, 1)::Int64
            │╻     -
  │   %14 = Base.llvmcall::Core.IntrinsicFunction
             ││╻╷╷╷  blockDim_x
  │   %15 = (%14)(Ptr{Nothing} @0x00000000023d4c08, UInt32,
Tuple{})::UInt32            │││┃││   _index
  │   %16 = (Core.zext_int)(Core.Int64, %15)::Int64
             ││││╻     toInt64
  │   %17 = Base.llvmcall::Core.IntrinsicFunction
             │││╻╷╷   _index
  │   %18 = (%17)(Ptr{Nothing} @0x000000000295ad78, UInt32,
Tuple{})::UInt32            ││││┃│    macro expansion
  │         (Core.zext_int)(Core.Int64, %18)
            ││││╻     toInt64
  │   %20 = Base.llvmcall::Core.IntrinsicFunction
             │││╻╷╷   _index
  │   %21 = (%20)(Ptr{Nothing} @0x00000000036dabf8, UInt32,
Tuple{})::UInt32            ││││┃│    macro expansion
  │         (Core.zext_int)(Core.Int64, %21)
            ││││╻     toInt64
  │   %23 = (Base.mul_int)(%13, %16)::Int64
             │╻     *
  │   %24 = Base.llvmcall::Core.IntrinsicFunction
             ││╻╷╷╷  threadIdx_x
  │   %25 = (%24)(Ptr{Nothing} @0x00000000035cb8d8, UInt32,
Tuple{})::UInt32            │││┃││   _index
  │   %26 = (Core.zext_int)(Core.Int64, %25)::Int64
             ││││╻     toInt64
  │   %27 = (Base.add_int)(%26, 1)::Int64
             │││╻     +
  │   %28 = Base.llvmcall::Core.IntrinsicFunction
             │││╻╷╷   _index
  │   %29 = (%28)(Ptr{Nothing} @0x00000000036cc848, UInt32,
Tuple{})::UInt32            ││││┃│    macro expansion
  │   %30 = (Core.zext_int)(Core.Int64, %29)::Int64
             ││││╻     toInt64
  │         (Base.add_int)(%30, 1)
            │││╻     +
  │   %32 = Base.llvmcall::Core.IntrinsicFunction
             │││╻╷╷   _index
  │   %33 = (%32)(Ptr{Nothing} @0x0000000002004d88, UInt32,
Tuple{})::UInt32            ││││┃│    macro expansion
  │   %34 = (Core.zext_int)(Core.Int64, %33)::Int64
             ││││╻     toInt64
  │         (Base.add_int)(%34, 1)
            │││╻     +
  │   %36 = (Base.add_int)(%23, %27)::Int64
             │╻     +
8 │   %37 = (Base.sub_int)(%36, 1)::Int64
             │╻     -
  │         (Main.div)(Main.Int, %37, Main.len)
             │
  │         $(Expr(:unreachable))
             │
  └──       $(Expr(:unreachable))
             │'''

... and then the same error. I see nothing special.



Em qui, 4 de out de 2018 às 18:58, Tim Besard <notifications@github.com>
escreveu:

**Comment by artalvpes** [comment]
Please ignore the first 5 lines.


Em qui, 4 de out de 2018 às 21:05, Artur Alves Pessoa <
artur.a.pessoa@gmail.com> escreveu:

**Comment by maleadt** [comment]
In that output, you can see:

```
  │         (Main.div)(Main.Int, %37, Main.len)                                                                                                                                                                  │     
  │         $(Expr(:unreachable))                                                                                                                                                                                │     
  └──       $(Expr(:unreachable))
```

i.e. the compiler asserts that the code following the call to `div` is unreachable. That's because your invocation of `div` is incorrect, and would result in a `MethodError` (as detected by the compiler, hence the `unreachable`).

```
julia> div(Int, 5, 5)
ERROR: MethodError: no method matching div(::Type{Int64}, ::Int64, ::Int64)
```

**Comment by maleadt** [comment]
Also, for these kinds of support questions (ie. not bugs) the Discourse forums are a better fit.

**Comment by artalvpes** [comment]
Thanks. I think I've got confused by the error message.



Em sex, 5 de out de 2018 às 10:12, Tim Besard <notifications@github.com>
escreveu:
