### ISSUE TITLE
Support for kwfuncs

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/CUDAnative.jl#274]
Since kwfuncs have gotten a lot faster in Julia 1.0, there usage is becoming more prevalent even in performant code.

In my case it was a call to `range(first(r) + x, length=length(r))`

```
Reason: unsupported call through a literal pointer (call to jl_get_keyword_sorter)
Stacktrace:
 [1] kwfunc at boot.jl:321
```

**Comment by maleadt** [comment]
Do we really always rely on the runtime to perform underspecified kwargs calls? I'll need to have a closer look, but that sees annoying to fix.

Somewhat related: one idea I've been toying with is to replace calls to runtime functions (either from Base like with `jl_get_keyword_sorter`, or when called from code emitted by codegen) by calls to Julia intrinsics and have those lowered to the CPU run-time in a late LLVM pass. CUDAnative would then have an easier time providing alternative implementations of runtime functions like this one.

**Comment by maleadt** [comment]
Most syntaxes seem supported

```
julia> @noinline inner(foobar;foo=1, bar=2) = nothing
inner (generic function with 2 methods)

julia> @cuda (()->inner(42;foo=1,bar=2))()

julia> @cuda (()->inner(42))()

julia> @cuda (()->inner(42;foo=1))()

julia> @cuda (()->inner(42;bar=2))()

julia> @cuda (()->inner(42;bar=2,foo=1))()
```

When exactly do we hit the kwsorted? Got an MWE?

**Comment by vchuravy** [comment]
This might be Julia version dependent then. I am on 1.0.0 and `CUDAnative#master`

```
julia> @noinline inner(foobar;foo=1, bar=2) = nothing
inner (generic function with 1 method)

julia> @cuda (()->inner(42;bar=2,foo=1))()
┌ Warning: unreachable control flow with multiple predecessors
└ @ CUDAnative ~/.julia/packages/CUDAnative/jRnXY/src/compiler/irgen.jl:433
ERROR: InvalidIRError: compiling #4() resulted in invalid LLVM IR
Reason: unsupported call through a literal pointer (call to jl_get_keyword_sorter)
Stacktrace:
 [1] kwfunc at boot.jl:321
 [2] #4 at REPL[3]:1
```

**Comment by maleadt** [comment]
Note sure about that, I don't have an older version handy. I thought you've upgraded since, does your use case work now? Either way, added a test to make sure it doesn't regress.
