### ISSUE TITLE
Warning: unreachable control flow with multiple predecessors

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/CUDAnative.jl#275]
In https://gist.github.com/vchuravy/64c7f5372f23f5673a46ce0195c521ef#file-kernelf_3-typed-jl I am triggering many instances of the `unreachable control flow` warning.
The actual problem might be hidden behind the invoke at the end of the function. 

```
┌ Warning: unreachable control flow with multiple predecessors
└ @ CUDAnative ~/.julia/packages/CUDAnative/nXHcX/src/compiler/irgen.jl:433
```

Maybe we can provide a backtrace for the warning? Or is that information not available at that time?

**Comment by maleadt** [comment]
> I am triggering many instances of the `unreachable control flow` warning.

With valid, GPU-compatible code, or in the case of code that later generates a validation error?

Also, this transformation happens at the LLVM IR level, so it would be most relevant to post that code. I didn't feel like it would be a good thing to dump all that IR to screen, esp. for a non-critical warning. Eagerly dumping to disk doesn't seem ideal either.


> Maybe we can provide a backtrace for the warning? Or is that information not available at that time?

We can back-trace to `@cuda`, and provide a pseudo back-trace to the source code pattern that generated the (unsupported) IR, but I don't think the latter is very valuable.

**Comment by maleadt** [comment]
The LLVM IR doesn't contain any `unreachable`, so this is probably optimized IR (the rewriting happens on unoptimized IR). Could you try https://github.com/JuliaGPU/CUDAnative.jl/pull/277 ?

**Comment by maleadt** [comment]
Anyhow, dup of #258, so let's continue there.
