### ISSUE TITLE
`@device_code` capture the entire call-tree

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/CUDAnative.jl#276]
It would be fantastic to have a way to get the entire call-tree of `@cuda` invocation.
I noticed in #274 that `@device_code` only captured the outer-most function and the code I wanted to look at is of the style:

```
function kernel(f::F, args...) where F
   # calculate I
   f(I, args...)
   return nothing
```

**Comment by maleadt** [comment]
`@device_code_llvm dump_module=true kernel(...)`?

**Comment by vchuravy** [comment]
Oh duh.

**Comment by vchuravy** [comment]
Double duh.

What I meant is that I would like to see the entire output from `device_code` (especially `code_typed` and `code_llvm`) of the call tree.
For the former I know that I can go in and find the `invoke` and paste that into my repl and for the latter `dump_module` works.
But yesterday I just wanted to do `@device_code everything=true dir="dump"`.

**Comment by maleadt** [comment]
OK, yeah that's a sensible request. Isn't that more of an upstream issue though, where this would be an interesting kwarg to eg. `code_typed` and `code_warntype`?
