### ISSUE TITLE
blackscholes.jl example MethodError

### ISSUE THREAD

**Issue by sbae0** [JuliaGPU/CUDAnative.jl#283]
Just started playing with julia today, blackscholes.jl gave MethodError posted below. Other examples finished without any errors. Found that zero($sptprice) inside main() is causing the issue. After replacing with zero(Float32, size($sptprice)) the output looks fine. Because I'm very new to julia this change might not be the best solution. My julia version is 1.0.2 on ubuntu 18.04 with nvidia-410 driver and CUDA10.

ERROR: LoadError: MethodError: no method matching zeros(::Array{Float32,1})
Closest candidates are:
  zeros(!Matched::Union{Integer, AbstractUnitRange}...) at array.jl:463
  zeros(!Matched::Type{StaticArrays.SArray{Tuple{N},T,1,N} where T}) where N at /home/sbae/.julia/packages/StaticArrays/WmJnA/src/SVector.jl:29
  zeros(!Matched::Type{StaticArrays.MArray{Tuple{N},T,1,N} where T}) where N at /home/sbae/.julia/packages/StaticArrays/WmJnA/src/MVector.jl:27
  ...

**Comment by maleadt** [comment]
Thanks for the report! `out` doesn't really need to be anything valid, it just needs to exist to survive until the `teardown` phase, so setting it to `nothing` is fine as well. Fixed in 3cb7fcffe105e42ae091fa9936fac0fefcb70510.
