### ISSUE TITLE
CuArray not defined when calling using CUDAnative

### ISSUE THREAD

**Issue by mohamed82008** [JuliaGPU/CUDAnative.jl#285]
It seems that CUDAdrv.jl removed `CuArray` in v1.0.0, but CUDAnative.jl still uses CUDAdrv.CuArray in https://github.com/JuliaGPU/CUDAnative.jl/blob/4cf3f30e79ae4615118d4274bcda384479d021c5/src/device/array.jl#L66 and https://github.com/JuliaGPU/CUDAnative.jl/blob/4cf3f30e79ae4615118d4274bcda384479d021c5/src/execution.jl#L132. This is causing the error `CuArray not defined` when calling `using CUDAnative`.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDAnative.jl/pull/284

**Comment by maleadt** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/19503
