### ISSUE TITLE
CUDAnative: problem with Julia install path on windows?

### ISSUE THREAD

**Issue by chrisk477** [JuliaGPU/CUDAnative.jl#300]
I just downloaded an installed Julia 1.0.2 64-bit on Windows 10. 

I accepted the default path [...]\AppData\Local\Julia-1.0.2

Testing CUDAnative gave me the following error:
ERROR: LoadError: InitError: error compiling __init__: could not load library "C:\Users\Christian\AppData\Local\Julia-1.0.0\bin\LLVM.dll"

Please note the "Julia-1.0.0" folder name (instead of "Julia-1.0.2").

Uninstalling Julia 1.0.2 and reinstalling it into the modified install path C:\Users\Christian\AppData\Local\Julia-1.0.0 resolved the issue.

**Comment by maleadt** [comment]
Try rebuilding LLVM; `Pkg.build("LLVM")`, or just `Pkg.build()` to rebuild all. You need to rebuild packages when your system changes.
