### ISSUE TITLE
Support for Cooperative Groups

### ISSUE THREAD

**Issue by Gnimuc** [JuliaGPU/CUDAnative.jl#323]
Cooperative group is a device level CUDA/C++ library, is it feasible to maintain a Julia version of it?

Resource: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#cooperative-groups

**Comment by maleadt** [comment]
Cooperative groups are supported by a fairly heavyweight C++ API, so this might not be be easy.
I also don't have experience with them, so maybe you could help out with:
1. C++ MWE(s) demonstrating/verifying pieces of functionality (the simpler the better)
2. proposed Julia API(s) to implement these features

**Comment by maleadt** [comment]
Fixed by https://github.com/JuliaGPU/CUDAnative.jl/pull/372
