### ISSUE TITLE
Example fails 

### ISSUE THREAD

**Issue by musm** [JuliaGPU/CUDAnative.jl#333]
I'm following https://docs.google.com/presentation/d/1l-BuAtyKgoVYakJSijaSqaTL3friESDyTOnU2OLqGoA/edit#slide=id.g49b2dd0131_0_102

```
julia> using CUDAnative
julia> function say(num)
        @cuprintf("Thread %ld says: %ld\n",
                  threadIdx().x, num)
        return
      end
julia> @cuda threads=4 say(42)
```
after some time the output I receive is
```
Thread 1 says: 0
Thread 1 says: 0
Thread 2 says: 0
Thread 3 says: 0
Thread 4 says: 0
```
which is clearly incorrect. 

Yet all CUDAnative.jl tests are passing

**Comment by maleadt** [comment]
Yeah, Windows.
https://github.com/JuliaGPU/CUDAnative.jl/blob/88d7ef93c14b611ade1b296c9bc1ee5818a14021/examples/hello_world.jl#L3-L13

**Comment by musm** [comment]
Thanks so I need to use `%lld`, perhaps it would be useful to document this somewhere or at least in the example PPT for new users.

**Comment by maleadt** [comment]
Snippets in these slides are not meant to be copy-pastable, and are often simplified to explain things better. I've added a speaker note though.
