### ISSUE TITLE
@cuprintf generated function throws with KeyError

### ISSUE THREAD

**Issue by colbec** [JuliaGPU/CUDAnative.jl#35]
A couple of issues with this example. The `@cuprintf` statement, according to the online docs, needs %ld and not %d. Secondly, with the previous change in place, in the message below line 7 refers to my `return` statement which is `return nothing` corrected from the bare `return` in the example code. Note that with the `@cuprintf` statement disabled, there is no problem the kernel returns correctly, and also if the `@cuprintf` prints only a simple string with no parameters there is also no problem.
I would suggest a PR but I can't get it to work.

```
> julia6 hello.jl 
ERROR: LoadError: error compiling hello_world: emit_invoke for /home/colin/cuda/hello.jl:7 requires the runtime language feature, which is disabled
Stacktrace:
 [1] _dump_function_linfo(::Core.MethodInstance, ::UInt64, ::Bool, ::Bool, ::Bool, ::Bool, ::Symbol, ::Bool, ::Base.CodegenParams) at ./reflection.jl:592
 [2] _dump_function(::ANY, ::ANY, ::Bool, ::Bool, ::Bool, ::Bool, ::Symbol, ::Bool, ::Base.CodegenParams) at ./reflection.jl:580
...
```
Using
```
julia> versioninfo()
Julia Version 0.6.0-dev.2481
Commit 2d86c42* (2017-01-30 22:50 UTC)
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by maleadt** [comment]
Confirmed. Bare return shouldn't matter, neither does the `%ld` (although that should be fixed). But the real problem is in the generated function backing `@cuprintf`, as is evident when making the following modification to inference:

```patch
diff --git a/base/inference.jl b/base/inference.jl
index 1cd127abe..8793deef0 100644
--- a/base/inference.jl
+++ b/base/inference.jl
@@ -1994,7 +1994,10 @@ function typeinf_frame(linfo::MethodInstance, caller, optimize::Bool, cached::Bo
             try
                 # user code might throw errors – ignore them
                 src = get_staged(linfo)
-            catch
+            catch ex
+                println("WARNING: An error occurred during generated function execution.")
+                println(ex)
+                ccall(:jlbacktrace, Void, ())
                 return nothing
             end
         else
```

-->

```
WARNING: An error occurred during generated function execution.
Base.KeyError(key=UInt32)
rec_backtrace at /home/tbesard/Projects/Julia-CUDA/julia/src/stackwalk.c:84
record_backtrace at /home/tbesard/Projects/Julia-CUDA/julia/src/task.c:239 [inlined]
jl_throw at /home/tbesard/Projects/Julia-CUDA/julia/src/task.c:565
getindex at ./dict.jl:474 [inlined]
#72 at ./<missing>:0
collect at ./array.jl:381
emit_vprintf at /home/tbesard/Projects/Julia-CUDA/CUDAnative/src/device/intrinsics.jl:170
jl_apply_generic at /home/tbesard/Projects/Julia-CUDA/julia/src/gf.c:2214
jl_apply at /home/tbesard/Projects/Julia-CUDA/julia/src/julia.h:1410 [inlined]
jl_f__apply at /home/tbesard/Projects/Julia-CUDA/julia/src/builtins.c:556
generated_cuprintf at /home/tbesard/Projects/Julia-CUDA/CUDAnative/src/device/intrinsics.jl:163
```

This at `f1e592e61d6898869b918331e3e625292f4c8cab`.

**Comment by vchuravy** [comment]
Maybe we should get the above into base hidden under a `verbose` statement?

**Comment by colbec** [comment]
@maleadt Thanks for the fixes, I can confirm that the latest master works fine with my GPU, all tests pass.
Just one comment on the print with %d and %ld - they produce quite different numbers, but the example code has the relevant "%d" which results in suitable output. This may orphan a comment in the [src code for intrinsics.jl](https://github.com/JuliaGPU/CUDAnative.jl/blob/master/src/device/intrinsics.jl) which refers to "Type widths need to match, eg. printing a Julia integer requires the `%ld` formatting string." Not sure about this but might lead to confusion.

**Comment by maleadt** [comment]
Sorry, I forgot about your comment on the formatting specifier.
Isn't `%d` correct though, as `threadIdx().x` and the like return a 32-bit integer? Might be better to use `%u` though, as I recently modified it to return unsigned values (5f64b42c90f5a02daa34bd3e25d57407e8bfda85).

I agree the comment is badly worded (`%ld` isn't necessary for Julia integers per se, but only when `Int == Int64`), but it still seems relevant to me.

**Comment by colbec** [comment]
Okay, my misunderstanding, there must be type conversions in effect, grid size parameters can go up as Int64 or even UInt8, but related indexes are UInt32. Got it.
