### ISSUE TITLE
│ Available CUDA toolchain does not provide libcudadevrt.

### ISSUE THREAD

**Issue by musm** [JuliaGPU/CUDAnative.jl#366]
Hi,

I have CUDA 10.1 installed. On windows I checked and I indeed have cudadevrt.lib  in the CUDA folder yet, CUDAnative complains 
```
┌ Error: Error building `CUDAnative`:
│ Available CUDA toolchain does not provide libcudadevrt.
```

**Comment by maleadt** [comment]
not `libcudadevrt.lib`?
@vchuravy https://github.com/JuliaGPU/CUDAapi.jl/blob/09b21004f27775efb0afbea8edcc03be16ec03fc/src/discovery.jl#L362

**Comment by musm** [comment]
Yep it's the wrong  name, it should be `cudadevrt.lib`
