### ISSUE TITLE
How to explicitly provide CUDA install location?

### ISSUE THREAD

**Issue by aterenin** [JuliaGPU/CUDAnative.jl#375]
I'm attempting to build CUDAnative on a shared system with multiple CUDA installations. I am NOT an administrator on this system.

I'd like to use CUDA 10. This is installed in `/usr/local/cuda-10.0/`. There is also a CUDA 9 installation on the system.

I get the error `Available CUDA toolchain does not provide libdevice.`.

I'm unable to find any information via Google on how to go about resolving this error.

**Comment by vchuravy** [comment]
Setting one of the environment variables `CUDA_PATH`, `CUDA_HOME`, or `CUDA_ROOT` should do the trick https://github.com/JuliaGPU/CUDAapi.jl/blob/master/src/discovery.jl#L205

**Comment by aterenin** [comment]
Thanks, setting `CUDA_PATH` was exactly what was needed. It'd be good to document this, though at minimum someone who is trying to figure this out can now at least find this GitHub issue.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDA.jl/commit/5036260a7520e82ee363a3f968425d602fe0976d
