### ISSUE TITLE
Random numbers in Kernel Function

### ISSUE THREAD

**Issue by waltsims** [JuliaGPU/CUDAnative.jl#40]
is there currently a way to generate cuRand like numbers in a kernel function or is this functionality planned for the future?

**Comment by SimonDanisch** [comment]
what demands to you have for your random numbers?!

**Comment by waltsims** [comment]
I would like to calculate high dimensional normal random vectors of floating point numbers for a numerical Monte Carlo simulation.  This has to happen often in some cases  in the order of 10^9 and more random numbers are necessary.  For this reason I'd like to avoid excessive copies from the host to the device.  cuRand offers such capabilities

**Comment by SimonDanisch** [comment]
I meant in terms of quality ;) There are some 3 liners to generate very simple random numbers on the GPU. I'm not exactly sure what the progress is on calling out to cuRand from inside a kernel, but seems like there was some improvement:
https://github.com/JuliaGPU/CUDAnative.jl/pull/2

**Comment by waltsims** [comment]
nominal quality is what i'm looking for for now! Thanks for much for the pointer! that looks promising :) 👍

**Comment by vchuravy** [comment]
I am currently updating https://github.com/JuliaGPU/CUDAnativelib.jl, and it provides an interface to cuRAND from a kernel function.
My plan is to add CUDAnativelib to METADATA soon. In any case I would encourage you to give https://github.com/JuliaGPU/CUDAnativelib.jl/tree/update a try and please do report any issues you run into.

**Comment by maleadt** [comment]
Awaiting CUDAnativelib, there's some quick & dirty implementation of `xorshift` I made for the Pagerank benchmark: [definition](https://github.com/JuliaParallel/PageRankBenchmark/blob/cbf510b75e80abf633f33cdc796fdb6e86fb5cfa/CUDA/kronGraph500NoPerm.jl#L8-L25), [invocation](https://github.com/JuliaParallel/PageRankBenchmark/blob/cbf510b75e80abf633f33cdc796fdb6e86fb5cfa/CUDA/kronGraph500NoPerm.jl#L69-L71). I haven't verified the quality of those numbers though.

**Comment by damiendr** [comment]
Here's another RNG that should be almost as easy to implement as xorshift and has good quality: http://www.pcg-random.org/download.html

**Comment by maleadt** [comment]
Going to close this, as this isn't a core feature of the compiler package. Random numbers will have to be implemented downstream, eg. at CuArrays, or in a to-be-created package with common functionality for GPU programming. CUDAstdlib.jl maybe?

**Comment by SimonDanisch** [comment]
Well, `CUDAstdlib` is something that GPUArrays is supposed to become and it will contain some simple rand kernels. Or do you mean a package that offers device kernels from e.g. CURAND?

**Comment by maleadt** [comment]
Yeah, I guess.
