### ISSUE TITLE
isodd and iseven

### ISSUE THREAD

**Issue by ali-ramadhan** [JuliaGPU/CUDAnative.jl#423]
Apparently it's non-trivial to figure out whether an integer is even or odd in a kernel as the `round` functions are not implemented (they're commented out) and the `mod` functions only accept floats. Turns out `CUDAnative.ffs` (find first set) can do it!

Is it a good idea to add `isodd` and `iseven` functions for CUDAnative via something like
```julia
isodd(k)  = ffs(k) == 1
iseven(k) = ffs(k) != 1
```

Not an issue but maybe more of a suggestion, as it took me a while to figure out how to determine whether an integer was even or odd in a kernel, and `Base.isodd` didn't work.

It's also very possible I completely missed an obvious way of doing this. I ran into this a few months ago so maybe things have changed. Happy to draft a tiny PR if that's not the case.

**Comment by vchuravy** [comment]
I wonder what is wrong with `_isodd(x) = (x & 1) == 1` :P

**Comment by ali-ramadhan** [comment]
Apparently `k & 1` was too obvious for my brain to see lol. Thanks!
