### ISSUE TITLE
Provide more informative error message if CUDA discovery fails

### ISSUE THREAD

**Issue by maxpkatz** [JuliaGPU/CUDAnative.jl#447]
Per JuliaGPU/CUDAapi.jl#87, if `find_toolkit()` in CUDAapi.jl discovery returns an empty list, CUDAnative will fail to build correctly:
```
┌ Error: Error building `CUDAnative`:
│ ERROR: LoadError: CUDA toolkit at  doesn't contain nvcc
```
It would be nice if a more informative error message were printed out here, so the user immediately knows that the problem is that no CUDA toolkit directory was found, so looking for `nvcc` there does not make sense.

**Comment by marius311** [comment]
As a CUDA*.jl noob that was just run around alot by this until I discovered this issue, I can confirm this would be a great addition. 

In fact, on the most recent versions of things (CUDAapi v1.2.0, CUDAdrv v4.0.3, CUDAnative v2.5.4) it doesn't appear like you even see this message unless you have `JULIA_DEBUG=CUDAnative` set. I was just getting an error from CUArrays that said `Cannot allocate before CuArrays has been initialized`, so it took quite a while to figure out that what had happened was that I was not loading the correct module on my GPU node and hence CUDA just wasn't getting detected.

**Comment by maleadt** [comment]
Should be much better now with artifacts.
