### ISSUE TITLE
Question: Is CUDAnative row major or column major?

### ISSUE THREAD

**Issue by veritas9872** [JuliaGPU/CUDAnative.jl#452]
Data ordering is very important when optimizing code.
However, I was unable to find a clear-cut answer to the question above while googling.
Julia is column major while CUDA C/C++ is row major.
What does CUDAnative use?
If it is column major, a lot of CUDA code will be sub-optimal when ported to CUDAnative.jl.

**Comment by jpsamaroo** [comment]
CUDAnative "just" compiles Julia code to PTX (via LLVM), so it follows the same array order semantics as Julia itself (column-major). CUDA C/C++ is a separate language entirely, and is row-major because C/C++ is row-major.

**Comment by veritas9872** [comment]
As a deep learning researcher, I am curious to know if this means that we have to use different indexing.
If CUDAnative is column-major, do we have to use WHCN ordering in deep learning tensors instead of NCHW as in CUDA C based programs?
Also, I am curious as to how the CUDA based libraries such as cuDNN could be ported to Julia without a serious makeover. Unless data re-ordering is hidden somewhere, there would be serious flaws in the output, or at least much slower code.
Even if Julia has equivalent speeds in naive code, the CUDA libraries have been optimized to give the best performance on the same hardware by utilizing very obscure and archaic features of NVIDIA GPUs.
Is it possible to use these libraries by calling the CUDA code from Julia after reordering the data, or do we have to re-implement the entire library with Julia's data ordering in mind?

**Comment by maleadt** [comment]
What Julian says; CUDAnative just compiles code. If you're allocating CuArrays, the rules are the same as with AbstractArray, so any kernels that work with CuArrays inputs and call get/setindex will use column major indexing (this can matter when optimizing kernels).


> Also, I am curious as to how the CUDA based libraries such as cuDNN could be ported to Julia without a serious makeover.

Such libraries typically allocate their own data using black-box handles, so this is not an issue. If you were to pass data that was allocated using e.g. CuArrays to a library that assumes row-major ordering, you'd need to reorder your data indeed.
