### ISSUE TITLE
@atomic does not error nicely

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAnative.jl#453]
```
julia> @cuda ((a)->(CUDAnative.@atomic a[2] = 42; nothing))(CuArray{Int}(undef, 1))
ERROR: LoadError: type Int64 has no field head
```

**Comment by UmashankarTriforce** [comment]
Is this issue still open?I would like to work on this issue. May I get more information on this?

**Comment by maleadt** [comment]
Sure! The idea is that the `@atomic` macro should be more robust, if a user misuses the macro it should report more nicely about what was wrong. You can look at the docstring/tests to see how the macro should be used, but it should definitely not throw an error as it does with the example here.

**Comment by UmashankarTriforce** [comment]
Thanks for the information! I'll have a look at code snippets and work out on a PR

**Comment by maleadt** [comment]
Let me know if there other issues you would be interested in helping out with, I am going to have a look at creating/tagging some more intro ones for Hacktoberfest after the weekend.

**Comment by UmashankarTriforce** [comment]
Sure I would love to have a look at other issues. I'm taking part in Hacktoberfest as well!
