### ISSUE TITLE
Tests failing on GTX 1660 ti

### ISSUE THREAD

**Issue by zot** [JuliaGPU/CUDAnative.jl#458]
I'm getting 18 test failures, Here's the [test output](https://github.com/JuliaGPU/CUDAnative.jl/files/3638239/CUDAnative-test-log.txt).

My info:

`CUDAnative version: v2.3.1`
`Card: NVIDIA GeForce GTX 1660 Ti`
`VBIOS Version: 90.16.26.00.11`
```
shell> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```
```
julia> versioninfo(verbose=true)
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Pop!_OS 19.04
  uname: Linux 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz: 
                 speed         user         nice          sys         idle          irq
       #1-12  4269 MHz     144890 s        425 s      46902 s    4159821 s          0 s
       
  Memory: 62.62921905517578 GB (54613.140625 MB free)
  Uptime: 3671.0 sec
  Load Avg:  0.662109375  0.85498046875  0.923828125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by zot** [comment]
Well, all the tests succeed if I test it inside the juliagpu/julia:v1.3-cuda docker image on the same machine so I must have a configuration problem...

**Comment by maleadt** [comment]
I haven't seen these errors before. But failing to load DelimitedFiles, a standard library, seems to indicate something is wrong with your julia binary/environment. Maybe that also explains the other errors, if `-g2` weren't passed through those tests would fail.

**Comment by zot** [comment]
Thanks, @maleadt! I tried renaming my .julia directory and when I ran Julia and did the tests, they succeeded.

Looks like I had bit-rot.
