### ISSUE TITLE
Fail to build in tmux?

### ISSUE THREAD

**Issue by xukai92** [JuliaGPU/CUDAnative.jl#469]
Same machine. Without tmux building was fine. Building in tmux gives me

```julia
┌ Info: Precompiling CUDAnative [be33ccc6-a3ff-5ff2-a52e-74243cff1e17]
└ @ Base loading.jl:1242
ERROR: LoadError: Available CUDA toolchain does not provide libdevice
```

Any idea why?

**Comment by maleadt** [comment]
tmux itself shouldn't make a difference, but try comparing the environment (`env`) in both. You might have some CUDA variables defined in one but not the other.

**Comment by xukai92** [comment]
The environment variable `CUDA_HOME` and `LD_LIBRARY_PATH` are the same.

In fact it might be some access issue on my sever where even I reinvoke in tmux, CUDAnative still cannot find `libdevice`. I restart tmux and everything is fine.

**Comment by xukai92** [comment]
Not sure if it's still be best place to post this but I still got some weird interaction between detecting GPU and tmux.

Basically, if I compile Flux outside tmux, the GPU is on (with this patch, not the new one in PR).
But if I simply do `tmux` and do the same thing in tmux, the GPU is not on.

I'm sure the both my CUDA_HOME and LD_LIBRARY_PATH is both exported as the same. In fact, in tmux, I can use CuArrays - so it's should not be a problem for this.

**Comment by maleadt** [comment]
It would be helpful if you could look into why the GPU isn't used (because it's unclear to me if you get the libdevice error, if Flux just doesn't use the GPU, etc). If it's the latter, `using CUDAapi, has_cuda()` should return false in tmux, and true outside of it. If that is the case, please run that command with `JULIA_DEBUG=CUDAapi`.

**Comment by xukai92** [comment]
`using CUDAapi; has_cuda()` gives me `true` inside tmux.

**Comment by xukai92** [comment]
Any idea how to diagnose this problem? I meet it again and it's reproducible.

**Comment by maleadt** [comment]
> If that is the case, please run that command with `JULIA_DEBUG=CUDAapi`.

Also compare `env` in- and outside tmux.

**Comment by xukai92** [comment]
Aha. It's funny. I was wrong about "CUDA_HOME and LD_LIBRARY_PATH are the same". I only checked if those in tmux are what I want but I didn't check outside (because the build was OK so I assumed they were what I want). In fact, these two variables are not set outside tmux somwhow and I guess the CUDA related path are automatically set. The sever I'm using has more than one version of CUDA avilable so it's likely the version found automatically is not the same as the version I pointed (which are cuda-9.2.148 and cuDNN-7.4.1.5_10.0). How do I check which versions are acutally used?

**Comment by xukai92** [comment]
I found it using `find_toolkit` form `CUDAapi` which gives me `cuda-8.0.44`. Now the question becomes why it doesn't compile with cuda-9.2.148?

**Comment by xukai92** [comment]
@maleadt I figured out the reason. It's actually related to `CUDAapi`. Basically I set `CUDA_HOME` by `CUDA_HOME=$CUDA_HOME:/opt/cuda-9.2.148`, which effectivly gives me `CUDA_HOME=:/opt/cuda-9.2.148` as the variable was empty. In this case, `find_toolkit` will ended up giving me `[":/opt/cuda-9.2.148"]`, which includes the ":" symbol. This then fails the finding of CUDA. Do you think this is something should be fixed? I beleive using `:` to support multiple possible paths is common.

**Comment by maleadt** [comment]
> Do you think this is something should be fixed? I beleive using `:` to support multiple possible paths is common.

At a quick glance it doesn't seem like other tools support this kind of syntax for CUDA related variables, and neither does any documentation. Furthermore, multiple CUDA installations aren't supported anyway, so I'm inclined not to add that kind of functionality.
