### ISSUE TITLE
blockDim() crashes Julia 1.3

### ISSUE THREAD

**Issue by braamvandyk** [JuliaGPU/CUDAnative.jl#512]
# Steps to reproduce:

julia> using CUDAnative

julia> blockDim()

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x2d781be0 -- unknown function (ip: 000000002D781BE0)
in expression starting at none:0
unknown function (ip: 000000002D781BDF)
Allocations: 26097088 (Pool: 26091007; Big: 6081); GC: 28

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x2e40f6e0 -- unknown function (ip: 000000002E40F6E0)
in expression starting at none:0
unknown function (ip: 000000002E40F6DF)
Allocations: 26097088 (Pool: 26091007; Big: 6081); GC: 28

# Julia version:

julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8

# Package versions
  [c5f51814] CUDAdrv v4.0.4
  [be33ccc6] CUDAnative v2.6.0
  [3a865a2d] CuArrays v1.5.0

Windows 10 Hom 64bit
CUDA Tookit 10.2

**Comment by maleadt** [comment]
Yeah, you can't execute GPU code on the CPU. Dup of https://github.com/JuliaGPU/CUDAnative.jl/issues/338
