### ISSUE TITLE
C++ compatible name mangling

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAnative.jl#556]
CUDA tools have this feature where different template instantiations of a single kernel are grouped in e.g. the profile view:

![image](https://user-images.githubusercontent.com/383068/74509006-be542000-4f00-11ea-8a6c-4c2e6a7ee0fb.png)

It would be nice if we mangle our names in the same way, with the kernel name (possibly configured to get rid of `anonymous`) as primary name, and the signature as template elements.

**Comment by vchuravy** [comment]
You have a funny definition of `It would be nice`, C++ name mangling is generally horrid :P 

Looking at LLVM it only implements a demangle, and the mangling is implemented in clang. So one would probably have to implement it manually.

**Comment by timholy** [comment]
There's the ancient [Cpp.jl](https://github.com/timholy/Cpp.jl) if it helps...

**Comment by maleadt** [comment]
![image](https://user-images.githubusercontent.com/383068/74728378-ea460d00-5242-11ea-93c8-775a3e7ac488.png)

Much better. PR incoming.
