### ISSUE TITLE
On Julia master: "Warning: Incompatibility detected between CUDA and LLVM 8.0+; disabling debug info emission for CUDA kernels"

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/CUDAnative.jl#569]
On Julia master, whenever I `import CUDANative`, I keep getting warnings like this:

```julia
┌ Warning: Incompatibility detected between CUDA and LLVM 8.0+; disabling debug info emission for CUDA kernels
└ @ CUDAnative ~/.julia/packages/CUDAnative/hfulr/src/CUDAnative.jl:114
```

Should I be worried about this? Is there anything I can do to fix this?

If it helps, here's the output of `nvcc --version`:
```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```

**Comment by maleadt** [comment]
I've silenced the warning: https://github.com/JuliaGPU/CUDAnative.jl/commit/dd12f6659c4ac6cbd3797a4b77706911e41effa5
Nothing you can do about right now, unless you want to debug NVPTX's DWARF printer :-)
