### ISSUE TITLE
Add detailed installation instructions

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGPU/CUDAnative.jl#59]
I found it a bit of a challenge getting CUDAnative.jl to build.  The steps I needed were:

1.  `brew cask install cuda`
2.  `export DYLD_LIBRARY_PATH="/usr/local/cuda/lib"`

**Comment by dlfivefifty** [comment]
In OS X of course

**Comment by maleadt** [comment]
Great, thanks. wrt. `DYLD_LIBRARY_PATH`, doesn't SIP disable that? That means we should _detect_ that path instead, and we currently have some heuristics already. Mostly, they look at eg. CUDA_PATH, CUDA_ROOT. Doesn't your set-up (after installing cuda with brew) set any of those?

**Comment by dlfivefifty** [comment]
No it doesn't set those. Settming them directly doesn't seem to work.
