### ISSUE TITLE
Cthulhu integration

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAnative.jl#597]
`@device_code_warntype interactive=true app()`

**Comment by maleadt** [comment]
@vchuravy are you ready to commit on an API (mainly just `descend_code_typed` and `descend_code_warntype`) and declare a 1.0? Makes it easier to manage the package as a dependency.

**Comment by vchuravy** [comment]
What you don't like my current integration? https://github.com/JuliaDebug/Cthulhu.jl/blob/14b2e068f41742e90f116284e288c24ea72ad849/src/reflection.jl#L82-L84 ;)

For me the question is backend and frontend integration. E.g. how does CUDAnative tell Cthulhu which about the method-instance hidden by `cufunction`, similar problems exist for `@async` and how does a frontend package interface with Cthulhu.

For the frontend the `descend_code_*` methods should be stable enough. Albeit you should take a look that they are currently in the form you want them to be. Happy to tag a 1.0 if that is the case.

**Comment by maleadt** [comment]
> For me the question is backend and frontend integration. E.g. how does CUDAnative tell Cthulhu which about the method-instance hidden by `cufunction`, similar problems exist for `@async` and how does a frontend package interface with Cthulhu.

Right now CUDAnative doesn't rewrite the function, so `(f,tt)` as captured by the compiler hook identifies the code executed? And even if we'd contextualize, wouldn't `(contextualize(f), tt)` cover that?
