### ISSUE TITLE
Is there a `@cushow` macro?

### ISSUE THREAD

**Issue by jw3126** [JuliaGPU/CUDAnative.jl#633]
I am new to gpu programming and think that at least for me a gpu analog of `@show` macro would be convenient for debugging and understanding how simple gpu programs work. Does such a macro exist? If not would a PR be welcome?

**Comment by maleadt** [comment]
What do you expect that macro to do; print on the GPU? We have `@cuprintln` for that, which is much more restricted in the types it can print; a GPU-compatible version of `@show` would require `show` which is currently not possible (we can't use Base formatting functionality because we don't support String or IO).

**Comment by jw3126** [comment]
I was imagining that it expands to something like this:
```julia
@cushow x
```
```julia
@cuprintln "x  = $x"
```
So same restrictions on types as `@cuprintln`.

**Comment by maleadt** [comment]
https://github.com/JuliaLang/julia/blob/b49d5ba3952bb1ce03ec55ab7ce0fa1cebd344fb/base/compiler/ssair/driver.jl#L8-L10 looks like a good implementation then :-) Want to create a PR with some tests?

**Comment by jw3126** [comment]
Yes I want to do a PR.

**Comment by jw3126** [comment]
I have trouble setting up dev version `CUDAnative`. If I do
`julia> using Pkg; pkg"dev CUDAnative"; using CUDAnative`
I get
```julia
...
[ Info: Precompiling CUDAnative [be33ccc6-a3ff-5ff2-a52e-74243cff1e17]
ERROR: LoadError: LoadError: UndefVarError: CompositeCompilerTarget not defined
```

**Comment by jw3126** [comment]
The following works with the stable version of `CUDAnative`. Any hints on the problem with the dev version would be great.
```julia
macro cushow(ex)
    val = gensym("val")
    s = string(ex)
    quote
        $val = $(esc(ex))
        CUDAnative.@cuprintln($(Expr(:string, s, " = ", val)))
        $val
    end
end
```

**Comment by maleadt** [comment]
> Any hints on the problem with the dev version would be great.

You also need to install GPUCompiler from the appropriate branch (generally master). The manifest encodes all this information.
