### ISSUE TITLE
Warning: `haskey(::TargetIterator, name::String)` is deprecated

### ISSUE THREAD

**Issue by samuela** [JuliaGPU/CUDAnative.jl#654]
I'm getting the following warning importing packages that depend on CUDAnative:
```
┌ Warning: `haskey(::TargetIterator, name::String)` is deprecated, use `Target(; name = name) !== nothing` instead.
│   caller = llvm_compat(::VersionNumber) at compatibility.jl:176
└ @ CUDAnative ~/.julia/packages/CUDAnative/C91oY/src/compatibility.jl:176
```
I'm on version
```
  [be33ccc6] CUDAnative v3.2.0
```

**Comment by maleadt** [comment]
CUDAnative is deprecated, this has been fixed in CUDA.jl.

The warning is harmless though, so if you need to continue using CUDAnative, either downgrade LLVM.jl or run with `--depwarn=no`.
