### ISSUE TITLE
UNKNOWN_ERROR(999) during build

### ISSUE THREAD

**Issue by nkottary** [JuliaGPU/CUDAnative.jl#72]
I get the following error on `Pkg.add("CUDAnative.jl")`.

```INFO: Cloning cache of CUDAdrv from https://github.com/JuliaGPU/CUDAdrv.jl.git
INFO: Cloning cache of CUDAnative from https://github.com/JuliaGPU/CUDAnative.jl.git
INFO: Cloning cache of LLVM from https://github.com/maleadt/LLVM.jl.git
INFO: Installing CUDAdrv v0.4.0
INFO: Installing CUDAnative v0.3.0
INFO: Installing LLVM v0.3.4
INFO: Building CUDAdrv
INFO: Building LLVM
INFO: Found 1 unique LLVM installations
WARNING: Only considering bundled LLVM v3.9.1 (define USE_SYSTEM_LLVM=1 to override)
INFO: Performing source build of LLVM extras library
INFO: Building CUDAnative
=============================[ ERROR: CUDAnative ]==============================

LoadError: InitError: CUDAdrv.CuError(999, Nullable{String}())
during initialization of module CUDAdrv
while loading /home/jrun/.julia/v0.6/CUDAnative/deps/build.jl, in expression starting on line 1

================================================================================
ERROR: UndefVarError: CUDAdrv not defined
deserialize_module(::SerializationState{IOStream}) at ./serialize.jl:754
handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:695
deserialize(::SerializationState{IOStream}) at ./serialize.jl:634
deserialize_datatype(::SerializationState{IOStream}, ::Bool) at ./serialize.jl:968
handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:674
deserialize(::SerializationState{IOStream}) at ./serialize.jl:634
handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:681
deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1075
handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:687
deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1075
handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:687
(::Base.Pkg.Entry.##54#55{Dict{Any,Any}})(::IOStream) at ./pkg/entry.jl:639
open(::Base.Pkg.Entry.##54#55{Dict{Any,Any}}, ::String, ::String) at ./iostream.jl:152
build!(::Array{String,1}, ::Dict{Any,Any}, ::Set{Any}) at ./pkg/entry.jl:636
build(::Array{String,1}) at ./pkg/entry.jl:650
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:570
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/entry.jl:479
edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where N) at ./pkg/entry.jl:30
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at ./task.jl:335
Stacktrace:
 [1] sync_end() at ./task.jl:287
 [2] macro expansion at ./task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:70
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at ./pkg/dir.jl:36
 [7] add(::String) at ./pkg/pkg.jl:117```

**Comment by nkottary** [comment]
I added `/usr/local/cuda/lib64/stubs` which contains `libcuda.so` to `LD_LIBRARY_PATH`. Now I get the following error:

```
INFO: Cloning cache of CUDAdrv from https://github.com/JuliaGPU/CUDAdrv.jl.git
INFO: Cloning cache of CUDAnative from https://github.com/JuliaGPU/CUDAnative.jl.git
INFO: Cloning cache of LLVM from https://github.com/maleadt/LLVM.jl.git
INFO: Installing CUDAdrv v0.4.0
INFO: Installing CUDAnative v0.3.0
INFO: Installing LLVM v0.3.4
INFO: Building CUDAdrv
===============================[ ERROR: CUDAdrv ]===============================

LoadError: Error -1 calling cuDriverGetVersion
while loading /home/jrun/.julia/v0.6/CUDAdrv/deps/build.jl, in expression starting on line 99

================================================================================
INFO: Building LLVM
INFO: Found 1 unique LLVM installations
WARNING: Only considering bundled LLVM v3.9.1 (define USE_SYSTEM_LLVM=1 to override)
INFO: Performing source build of LLVM extras library
INFO: Building CUDAnative
ERROR: LoadError: Unable to load dependency file /home/jrun/.julia/v0.6/CUDAdrv/deps/ext.jl.
Please run Pkg.build("CUDAdrv") and restart Julia.
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:569
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /home/jrun/.julia/v0.6/CUDAdrv/src/CUDAdrv.jl, in expression starting on line 19
=============================[ ERROR: CUDAnative ]==============================

LoadError: Failed to precompile CUDAdrv to /home/jrun/.julia/lib/v0.6/CUDAdrv.ji.
while loading /home/jrun/.julia/v0.6/CUDAnative/deps/build.jl, in expression starting on line 1

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: CUDAnative and CUDAdrv had build errors.

 - packages with build errors remain installed in /home/jrun/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("CUDAnative", "CUDAdrv")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
```

**Comment by maleadt** [comment]
Something seems iffy with your set-up. In your first post, CUDAdrv has built correctly (ie. it had already picked up `libcuda.so`) but using it from CUDAnative's build script results in error 999, aka. unknown error.
In your second post, `cuDriverGetVersion` returns -1 which isn't a valid CUDA error code.

Are your sure your set-up is working properly? Which `libcuda` was picked up in the first case (inspect `ext.jl` after building CUDAdrv)?

**Comment by maleadt** [comment]
Did you load the kernel driver? Not having done so would explain error 999. On 14 Jun 2017 18:25, "Nishanth H. Kottary" <notifications@github.com> wrote:I added /usr/local/cuda/lib64/stubs which contains libcuda.so to LD_LIBRARY_PATH. Now I get the following error:
INFO: Cloning cache of CUDAdrv from https://github.com/JuliaGPU/CUDAdrv.jl.git
INFO: Cloning cache of CUDAnative from https://github.com/JuliaGPU/CUDAnative.jl.git
INFO: Cloning cache of LLVM from https://github.com/maleadt/LLVM.jl.git
INFO: Installing CUDAdrv v0.4.0
INFO: Installing CUDAnative v0.3.0
INFO: Installing LLVM v0.3.4
INFO: Building CUDAdrv
===============================[ ERROR: CUDAdrv ]===============================

LoadError: Error -1 calling cuDriverGetVersion
while loading /home/jrun/.julia/v0.6/CUDAdrv/deps/build.jl, in expression starting on line 99

================================================================================
INFO: Building LLVM
INFO: Found 1 unique LLVM installations
WARNING: Only considering bundled LLVM v3.9.1 (define USE_SYSTEM_LLVM=1 to override)
INFO: Performing source build of LLVM extras library
INFO: Building CUDAnative
ERROR: LoadError: Unable to load dependency file /home/jrun/.julia/v0.6/CUDAdrv/deps/ext.jl.
Please run Pkg.build("CUDAdrv") and restart Julia.
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:569
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /home/jrun/.julia/v0.6/CUDAdrv/src/CUDAdrv.jl, in expression starting on line 19
=============================[ ERROR: CUDAnative ]==============================

LoadError: Failed to precompile CUDAdrv to /home/jrun/.julia/lib/v0.6/CUDAdrv.ji.
while loading /home/jrun/.julia/v0.6/CUDAnative/deps/build.jl, in expression starting on line 1

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: CUDAnative and CUDAdrv had build errors.

 - packages with build errors remain installed in /home/jrun/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("CUDAnative", "CUDAdrv")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

**Comment by maleadt** [comment]
Looking at those stubs, which I didn't knew existed:
```
00000000000050b0 <cuDriverGetVersion@@Base>:
    50b0:       b8 ff ff ff ff          mov    $0xffffffff,%eax
    50b5:       c3                      retq   
    50b6:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
    50bd:       00 00 00
```

so all of the API functions just return -1. You _definitely_ shouldn't be using those libraries as basis for CUDAdrv (which built correctly, so didn't need any `LD_LIBRARY_PATH`)

Summarizing, I think that you just haven't loaded the (correct, or any) nvidia kernel module. You can verify this using `nvidia-smi`, which should execute properly and list any available GPUs (because even if `nvidia.ko` is loaded, if there's no GPU detected `CUDAdrv`/`CUDAnative` will fail anyway).

I should probably document this a bit better though.

**Comment by nkottary** [comment]
The kernel seems to have loaded properly, here's the output of `nvidia-smi`:
```
$ nvidia-smi
Sat Jun 17 22:19:23 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | DEA8:00:00.0     Off |                    0 |
| N/A   53C    P8    29W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I checked out CUDAdrv.jl and built CUDAnative.jl:
```
INFO: Cloning CUDAdrv from https://github.com/JuliaGPU/CUDAdrv.jl
INFO: Computing changes...
INFO: No packages to install, update or remove
INFO: Package database updated
INFO: Cloning cache of CUDAnative from https://github.com/JuliaGPU/CUDAnative.jl.git
INFO: Cloning cache of LLVM from https://github.com/maleadt/LLVM.jl.git
INFO: Installing CUDAnative v0.3.0
INFO: Installing LLVM v0.3.4
INFO: Building LLVM
INFO: Found 1 unique LLVM installations
WARNING: Only considering bundled LLVM v3.9.1 (define USE_SYSTEM_LLVM=1 to override)
INFO: Performing source build of LLVM extras library
INFO: Building CUDAdrv
===============================[ ERROR: CUDAdrv ]===============================

LoadError: CUDA error 999 calling cuInit
while loading /home/jrun/.julia/v0.6/CUDAdrv/deps/build.jl, in expression starting on line 107

================================================================================
INFO: Building CUDAnative
ERROR: LoadError: Unable to load dependency file /home/jrun/.julia/v0.6/CUDAdrv/deps/ext.jl.
Please run Pkg.build("CUDAdrv") and restart Julia.
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:569
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /home/jrun/.julia/v0.6/CUDAdrv/src/CUDAdrv.jl, in expression starting on line 18
```

**Comment by maleadt** [comment]
Did you try running CUDA code? Does that work?
There might be some permission issue (ie. on the nvidia char device), although running `nvidia-smi` as non-root seems to work...

I'll have a look when I have some time.

**Comment by aviks** [comment]
The julia in the currently deployed cluster is not a source build, but when we are trying to build CUDANative, its on a source build.

**Comment by maleadt** [comment]
That means I'm working with a different Julia here? That's making it hard to find an issue (apart from the fact I almost never can load gpu.juliabox.com), especially because everything I'm testing seems to work fine:

> julia> ccall((:cuInit, "libcuda"), Cint, (Cint,), 0)
> 0

ie. success, while you report `LoadError: CUDA error 999 calling cuInit`. And I cannot run tests, or inspect `ext.jl`, because where is CUDAdrv even installed? The output of `Pkg.dir` is nonsensical, and as you mentioned in the mail thread `Pkg` operations aren't even supposed to be working...

FYI, that source-build is only necessary for building LLVM.jl, which in turn builds a `libLLVM_extra.so`. After that, no source builds are required.

**Comment by maleadt** [comment]
Some more detailed instructions on (debugging the process on) getting CUDAnative.jl working:

First of all, you need a source build to `Pkg.build` LLVM.jl, which builds an additional `libLLVM_extra.so` built against Julia's `libLLVM`. The generated `ext.jl` will contain hard-coded paths and build-time info about the set-up, so that information _has_ to match between the source-build of Julia used to `Pkg.build("LLVM")` and the one used to load LLVM.jl. At load-time, the package also does an mtime check to see if the package needs to be rebuild, so there might be an issue there (but that's non-critical).

CUDAdrv shouldn't be an issue to build/test, if there is this is probably an issue with your environment (as is the case here). In essence, CUDAdrv's `build.jl` detects your CUDA path, version, and calls `cuInit` to see if everything is working. In your case, the build script fails to run `cuInit`, although I've been able to do so using the system `libcuda` at `Libdl.dlpath(Libdl.dlopen("libcuda"))` (can't run this because `gpu.juliabox.com` is timing out again). Either there is a difference between the environment in which you've run `Pkg.build("CUDAdrv")` and the one I've run `ccall(:cuInit)` in (through jupyter's terminal), or different libraries are being picked up. You can run `Pkg.build("CUDAdrv")` using the `DEBUG=1` environment flag, which'll print the path of the library detected, and compare that to the output of `dlpath`.

After that, `CUDAnative` should `Pkg.build` just fine. Similarly to CUDAdrv, it detects the path of your CUDA set-up (overridable using env vars), in order to find `libdevice`.

**Comment by nkottary** [comment]
So when we try to build LLVM.jl from the source buid, we see the following error. It seems it is trying to use the bundled LLVM, so not sure what is wrong. any ideas?

```
INFO: Cloning cache of LLVM from https://github.com/maleadt/LLVM.jl.git
INFO: Installing LLVM v0.3.4
INFO: Building LLVM
INFO: Found 1 unique LLVM installations
WARNING: Only considering bundled LLVM v3.9.1 (define USE_SYSTEM_LLVM=1 to override)
INFO: Performing source build of LLVM extras library
================================[ ERROR: LLVM ]=================================

LoadError: could not load library "/home/jrun/.julia/v0.6/LLVM/deps/llvm-extra/libLLVM_extra.so"
/home/jrun/.julia/v0.6/LLVM/deps/llvm-extra/libLLVM_extra.so: undefined symbol: _ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKSs
while loading /home/jrun/.julia/v0.6/LLVM/deps/build.jl, in expression starting on line 42

================================================================================

```

**Comment by maleadt** [comment]
https://maleadt.github.io/LLVM.jl/latest/man/troubleshooting.html#Building-llvm-extra-fails-due-to-C11-ABI-issues-1

Using the same compiler as the source build?

**Comment by aviks** [comment]
Ok, thanks. So .....

Julia was built with GCC 5.1. However, we then switched to GCC 4.9 in the docker images since that is a requirement of CUDArt apparently. That works, and GPUArrays + OpenCL works as well. 

Now, to compile LLVM.jl, we need to switch back to gcc 5.1. If we do that, will there be issues at runtime. Does nvcc depend on GCC at runtime? Can it work with GCC 5.1?

**Comment by maleadt** [comment]
You don't need to switch, just make sure `libLLVM_extra` is compiled with the same compiler Julia was compiled with. You can install it temporarily, and "pass" it to `Pkg.build` by defining the CC/CXX environment variables.

And it's not a requirement of CUDArt, but a requirement of your CUDA version.

**Comment by maleadt** [comment]
Any progress here? As far as I can see on `gpu.juliabox.com`, CUDAdrv now works properly all of a sudden? What was the issue?

Have you been able to build LLVM.jl, and subsequently CUDAnative.jl?

**Comment by nkottary** [comment]
LLVM.jl seems to have built successfully. Trying CUDAnative.jl now...

**Comment by nkottary** [comment]
It seems the docker build only sort of detects the gpu, for example Knet.jl build detects the GPU from inside the container but some packages like CUDArt and CUDAnative dont. But in runtime all packages detect GPU properly from inside the container.

So after you login you will need to run:

```
Pkg.build("CUDArt")
Pkg.add("CUDAnative")
```

(Note that the effect of the above commands will go away when you logout. But I think its tolerable as the above commands only take about 30 seconds to run)
