### ISSUE TITLE
NVPTX does not support Julia's address spaces

### ISSUE THREAD

**Issue by colbec** [JuliaGPU/CUDAnative.jl#73]
CUDAdrv tests ok, but when I test CUDAnative with:

```
Julia Version 0.7.0-DEV.665
Commit 401b724fbb (2017-06-20 06:22 UTC)
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:

Pkg.status("CUDAnative")
 - CUDAnative                    0.3.0+             master
```
I get the eponymous error related to LLVMAddLowerGCFramePass.
Do I have a version issue here?

**Comment by maleadt** [comment]
Yes, I know, CUDAnative is currently broken on master after JuliaLang/julia#21888. I haven't had the time to fix, please use `release-0.6` or `v0.6.0` for the time being.

**Comment by colbec** [comment]
Now that the final binary has been released for Julia 0.6 I have switched to this for my main work. Since I did not compile from source, is there a way to match up CUDA tools with the binary version of 0.6? Currently the installation calls for the custom compile approach.

**Comment by maleadt** [comment]
The source build is required for LLVM.jl, which builds a custom `libLLVM_extra.so`. The problem with binary dists is that 1) it doesn't ship the necessary build artifacts (`llvm-config`, LLVM headers, etc), and 2) there's going to be a compiler mismatch (the one used to build julia's binary LLVM, and the one you're using to build `libLLVM_extra`). The former you could "fix" by building `libLLVM_extra` once and caching that .so, the second issue you cannot fix. It _might_ work, but there might be incompatibilities.

**Comment by maleadt** [comment]
**Triaged**: after JuliaLang/julia#21888, Julia emits address spaces (on function parameters, loads, addrspacecasts and in the future possibly alloca's) on points in non-generic address spaces. NVPTX's ISEL doesn't support these, and we need to strip them from the IR. LLVM.jl isn't powerful enough for this, as the C API doesn't export any of Utils/CloneFunction, so we'd need to do this as part of base (ref JuliaLang/julia#22414).
