### ISSUE TITLE
Parameterize CuDeviceArray on its address space

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAnative.jl#79]
In some cases (ie. shared memory allocated in the same function) LLVM can infer the AS, but in most cases (eg. all global loads) we don't. This results in generic `ld` instructions, which can be slower and have different cache behaviour.

Solution: add an address space argument to the `pointerref` and `pointerset` intrinsics, allowing us to perform "AS-typed" loads from `getindex` and `setindex!`.

Alternative solution: add an AS type parameter to `Ptr`, but that's quite insane.

This probably accounts for the 60% slowdown in Rodinia's `nw` benchmark, where after warm-up the overhead disappears, as well as using larger data sets, possibly indicating a caching issue.

**Comment by vchuravy** [comment]
I don't find the AS type parameter solution to be quite that insane. IIUC that is actually the way AS pointers are modeled in the LLVM langref.
