### ISSUE TITLE
Implement a simulator for execution on GPU

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/CUDAnative.jl#8]
In the long run it will be helpful to have a simulator that executes code natively through threads (or even purely sequential).

**Comment by maleadt** [comment]
For sure. It'll have to wait until we have proper target-based dispatch though, at which point we might just be able to provide CPU-target counterparts for all intrinsics. Although this might be quite hard for intrinsics which implicitly share state with other threads or blocks (shared memory, voting, etc).

**Comment by maleadt** [comment]
Closing some of the speculative/too ambitious issues.

Target-based dispatch has become a non-goal anyway, except for math intrinsics.
