### ISSUE TITLE
code_llvm etc

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CUDAnative.jl#92]
It seems strange for CUDAnative to export these functions -- given the conflict with Base, it doesn't actually make them any easier to use (you still have to qualify or import) but *does* stop you using the Base versions (which I end up doing quite frequently to debug specialisation issues).

Is there another reason to do this that I'm missing?

**Comment by maleadt** [comment]
There's two main reasons I decided to intentionally conflict with Base:
1. we hook parts of codegen (irgen, different MC jit, and in the future different inference) so the results are bound to be different; using Base's reflection utils for CUDA code is wrong
2. CUDAnative's reflection utils support being stuck in front of `@cuda (...) kernel(...)`, in which case the reflection methods will be called with `kernel=true` (which again yields different codegen)

Both these make that it is inconvenient (doesn't support `@cuda`) and often wrong to use Base's reflection utils, which I wanted to make clear to the user by intentionally introducing a conflict. Just introducing `@cuda_code_llvm` or smth (which looks ugly as hell) wouldn't make that as clear.

**Comment by MikeInnes** [comment]
Ok, that does make sense. Didn't quite have the right effect as I just stubbornly used the base versions anyway :)

I suspect that a writeup of your workflow when putting kernels together -- including common errors, debugging specialisation issues, the `code_*` tools -- would be hugely valuable, if you're able to put something together.
