### ISSUE TITLE
Method errors get reported as `InexactError`

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CUDAnative.jl#95]
would be nice to catch this early

**Comment by maleadt** [comment]
What kind of method errors, those in kernels or calling kernels? Got a repro?

**Comment by MikeInnes** [comment]
Calling kernels -- easy enough to reproduce by calling `@cuda (1,len) kernel_vadd(d_a, d_b, d_c)` with one fewer argument, for example.

I though I'd seen it inside kernels as well, but couldn't immediately reproduce it -- will keep an eye out.
